### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'sock'

### ISSUE THREAD

**Issue by phord** [linkchecker/linkchecker#157]
********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://blog.purestorage.com/industries, started 140556822898432)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://blog.purestorage.com/industries, started 140556822898432)>>
      url_data = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fd610cd7c80>
      url_data = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self = <local> <Checker(CheckThread-https://blog.purestorage.com/industries, started 140556822898432)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fd610579c90>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/i...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purest...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 135, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorag...
      request = <local> <PreparedRequest [GET]>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 165, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestora...
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'allow_redirects': False, 'verify': True, 'stream': True, 'timeout': 60}
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 172, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestora...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 193, in _add_ssl_info
    line: sock = self._get_ssl_sock()
    locals:
      sock = <not found>
      self = <local> <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestorage.com/industries>
      self._get_ssl_sock = <local> <bound method HttpUrl._get_ssl_sock of <https link, base_url=u'https://blog.purestorage.com/industries', parent_url=u'https://blog.purestorage.com/industries/', base_ref=None, recursion_level=2, url_connection=None, line=26, column=1, page=0, name=u'', anchor=u'', cache_url=https://blog.purestora...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 184, in _get_ssl_sock
    line: if raw_connection.sock is None:
    locals:
      raw_connection = <local> None
      raw_connection.sock = <local> !AttributeError: 'NoneType' object has no attribute 'sock'
      None = <builtin> None
AttributeError: 'NoneType' object has no attribute 'sock'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Requests: 2.18.4
Modules: Argcomplete, Sqlite
Local time: 2018-05-31 16:28:16-007
sys.argv: ['/usr/bin/linkchecker', '--ignore-url', 'https://blog.purestorage.com/xmlrpc.php', 'https://blog.purestorage.com/']
LC_CTYPE = 'en_US.UTF-8'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********

**Comment by lacymorrow** [comment]
Installing via APT I received version 9.3 and this error, would be good to bump the apt version

**Comment by anarcat** [comment]
the version in Debian was updated, you need to upgrade to buster, buster. ;)
