### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#165]
## Summary

When trying to check links in a local html file, linkchecker outputs an error on the console.

## Steps to reproduce

 1. check links in a local html file by the following command `linkchecker myfile.html`

## Actual result

```log
INFO 2018-06-27 11:02:33,317 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 570, in <module>
    aggregate_url(aggregate, strformat.stripurl(url))
  File "/usr/lib/python2.7/dist-packages/linkcheck/cmdline.py", line 70, in aggregate_url
    url_data = get_url_from(url, 0, aggregate, extern=(0, 0))
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/__init__.py", line 125, in get_url_from
    line=line, column=column, page=page, name=name, extern=extern)
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 118, in __init__
    self.check_syntax()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 323, in check_syntax
    self.build_url()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/fileurl.py", line 136, in build_url
    self.build_base_url()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/fileurl.py", line 116, in build_base_url
    base_url = os.getcwd()+"/"+base_url
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

## Expected result

no error

## Environment

 * Operating system: Debian GNU/Linux 9.4 (stretch)
 * Linkchecker version: LinkChecker 9.3 released 16.7.2014
 * Python version: Python 2.7.13
 * Install method: distribution package
 * Site URL: local file

## Configuration file

nothing specific

```
# Sample configuration file; see the linkcheckerrc(5) man page or
# execute linkchecker -h for help on these options.
# Commandline or GUI options override these settings.

##################### output configuration ##########################
[output]
# enable debug messages; see 'linkchecker -h' for valid debug names
#debug=all
# print status output
#status=1
# change the logging type
#log=xml
# turn on/off --verbose
#verbose=1
# turn on/off --warnings
#warnings=0
# turn on/off --quiet
#quiet=1
# additional file output
#fileoutput = text, html, gml, sql


##################### logger configuration ##########################
# Note that the logger configuration is ignored by the linkchecker-gui
# program. Results in the GUI can be saved to a file with the command
# File -> Save results.
#
# logger output part names:
# all       For all parts
# realurl   The full url link
# result    Valid or invalid, with messages
# extern    1 or 0, only in some logger types reported
# base      <base href=...>
# name      <a href=...>name</a> and <img alt="name">
# parenturl The referrer URL if there is any
# info      Some additional info, e.g. FTP welcome messages
# warning   Warnings
# dltime    Download time
# checktime Check time
# url       The original url name, can be relative
# intro     The blurb at the beginning, "starting at ..."
# outro     The blurb at the end, "found x errors ..."
# stats     Statistics including URL lengths and contents.

# each Logger can have separate configuration parameters

# standard text logger
[text]
#filename=linkchecker-out.txt
#parts=all
# colors for the various parts, syntax is <color> or <type>;<color>
# type can be bold, light, blink, invert
# color can be default, black, red, green, yellow, blue, purple, cyan, white,
# Black, Red, Green, Yellow, Blue, Purple, Cyan, White
#colorparent=white
#colorurl=default
#colorname=default
#colorreal=cyan
#colorbase=purple
#colorvalid=bold;green
#colorinvalid=bold;red
#colorinfo=default
#colorwarning=bold;yellow
#colordltime=default
#colorreset=default

# GML logger
[gml]
#filename=linkchecker-out.gml
#parts=all
# valid encodings are listed in http://docs.python.org/library/codecs.html#standard-encodings
# default encoding is iso-8859-15
#encoding=utf_16

# DOT logger
[dot]
#filename=linkchecker-out.dot
#parts=all
# default encoding is ascii since the original DOT format does not
# support other charsets
#encoding=iso-8859-15

# CSV logger
[csv]
#filename=linkchecker-out.csv
#separator=,
#quotechar="
#parts=all

# SQL logger
[sql]
#filename=linkchecker-out.sql
#dbname=linksdb
#separator=;
#parts=all

# HTML logger
[html]
#filename=linkchecker-out.html
# colors for the various parts
#colorbackground=#fff7e5
#colorurl=#dcd5cf
#colorborder=#000000
#colorlink=#191c83
#colorwarning=#e0954e
#colorerror=#db4930
#colorok=#3ba557
#parts=all

# blacklist logger
[blacklist]
#filename=~/.linkchecker/blacklist

# custom xml logger
[xml]
#encoding=iso-8859-1

# GraphXML logger
[gxml]
#encoding=iso-8859-1

# Sitemap logger
[sitemap]
#priority=0.7
#frequency=weekly


##################### checking options ##########################
[checking]
# number of threads
#threads=100
# connection timeout in seconds
#timeout=60
# Time to wait for checks to finish after the user aborts the first time
# (with Ctrl-C or the abort button).
#aborttimeout=300
# The recursion level determines how many times links inside pages are followed.
#recursionlevel=1
# Basic NNTP server. Overrides NNTP_SERVER environment variable.
#nntpserver=
# parse a cookiefile for initial cookie data
#cookiefile=/path/to/cookies.txt
# User-Agent header string to send to HTTP web servers
# Note that robots.txt are always checked with the original User-Agent.
#useragent=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
# When checking finishes, write a memory dump to a temporary file.
# The memory dump is written both when checking finishes normally
# and when checking gets canceled.
# The memory dump only works if the python-meliae package is installed.
# Otherwise a warning is printed to install it.
#debugmemory=0
# When checking absolute URLs inside local files, the given root directory
# is used as base URL.
# Note that the given directory must have URL syntax, so it must use a slash
# to join directories instead of a backslash.
# And the given directory must end with a slash.
# Unix example:
#localwebroot=/var/www/
# Windows example:
#localwebroot=/C|/public_html/
# Check SSL certificates. Set to an absolute pathname for a custom
# CA cert bundle to use. Set to zero to disable SSL certificate verification.
#sslverify=1
# Stop checking new URLs after the given number of seconds. Same as if the
# user hits Ctrl-C after X seconds.
#maxrunseconds=600
# Maximum number of URLs to check. New URLs will not be queued after the
# given number of URLs is checked.
#maxnumurls=153
# Maximum number of requests per second to one host.
#maxrequestspersecond=10
# Allowed URL schemes as a comma-separated list.
#allowedschemes=http,https

##################### filtering options ##########################
[filtering]
#ignore=
# ignore everything with 'lconline' in the URL name
#  lconline
# and ignore everything with 'bookmark' in the URL name
#  bookmark
# and ignore all mailto: URLs
#  ^mailto:
# do not recurse into the following URLs

#nofollow=
# just an example
#  http://www\.example\.com/bla

# Ignore specified warnings (see linkchecker -h for the list of
# recognized warnings). Add a comma-separated list of warnings here
# that prevent a valid URL from being logged. Note that the warning
# will be logged in invalid URLs.
#ignorewarnings=url-unicode-domain
# Regular expression to add more URLs recognized as internal links.
# Default is that URLs given on the command line are internal.
#internlinks=^http://www\.example\.net/
# Check external links
#checkextern=1


##################### password authentication ##########################
[authentication]
# WARNING: if you store passwords in this configuration entry, make sure the
# configuration file is not readable by other users.
# Different user/password pairs for different URLs can be provided.
# Entries are a triple (URL regular expression, username, password),
# separated by whitespace.
# If the regular expression matches, the given user/password pair is used
# for authentication. The commandline options -u,-p match every link
# and therefore override the entries given here. The first match wins.
# At the moment, authentication is used for http[s] and ftp links.
#entry=
# Note that passwords are optional. If any passwords are stored here,
# this file should not readable by other users.
#  ^https?://www\.example\.com/~calvin/ calvin mypass
#  ^ftp://www\.example\.com/secret/ calvin

# if the website requires a login the URL and optionally the user and
# password CGI fieldnames can be provided.
#loginurl=http://www.example.com/

# The name of the user and password CGI field
#loginuserfield=login
#loginpasswordfield=password
# Optionally any additional CGI name/value pairs. Note that the default
# values are submitted automatically.
#loginextrafields=
#  name1:value1
#  name 2:value 2

############################ Plugins ###################################
#
# uncomment sections to enable plugins

# Check HTML anchors
#[AnchorCheck]

# Print HTTP header info
#[HttpHeaderInfo]
# Comma separated list of header prefixes to print.
# The names are case insensitive.
# The default list is empty, so it should be non-empty when activating
# this plugin.
#prefixes=Server,X-

# Add country info to URLs
#[LocationInfo]

# Run W3C syntax checks
#[CssSyntaxCheck]
#[HtmlSyntaxCheck]

# Search for regular expression in page contents
#[RegexCheck]
#warningregex=Oracle Error

# Search for viruses in page contents
#[VirusCheck]
#clamavconf=/etc/clamav/clam.conf

# Check that SSL certificates are at least the given number of days valid.
#[SslCertificateCheck]
#sslcertwarndays=14

# Parse and check links in PDF files
#[PdfParser]

# Parse and check links in Word files
#[WordParser]
```

## Logs

```log
linkchecker myfile.html
INFO 2018-06-27 11:10:02,089 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
Traceback (most recent call last):
  File "/usr/bin/linkchecker", line 570, in <module>
    aggregate_url(aggregate, strformat.stripurl(url))
  File "/usr/lib/python2.7/dist-packages/linkcheck/cmdline.py", line 70, in aggregate_url
    url_data = get_url_from(url, 0, aggregate, extern=(0, 0))
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/__init__.py", line 125, in get_url_from
    line=line, column=column, page=page, name=name, extern=extern)
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 118, in __init__
    self.check_syntax()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 323, in check_syntax
    self.build_url()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/fileurl.py", line 136, in build_url
    self.build_base_url()
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/fileurl.py", line 116, in build_base_url
    base_url = os.getcwd()+"/"+base_url
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
```

**Comment by oupala** [comment]
I'm running linkchecker from the directory where my html is located. I mean I want to check a local file.

```bash
>python -c "import os; print(os.getcwd())"
/home/user/Download/checklinks
```

And the html file I want to check is `/home/user/Download/checklinks/myfile.html`.

So my command is:

```bash
~/Download/checklinks>linkchecker myfile.html
```

**Comment by anarcat** [comment]
the user is actually called `user`?? the reason why I am asking the actual path is I suspect the directory is some in weird encoding that would trigger such exception...

**Comment by oupala** [comment]
No the user is not actually called user. I changed the username for privacy prupose.

But you're right, it had something to do with the path. It is not linked to the username, which is composed only of ascii characters. But the full path includes some characters that are not ascii. As the user speaks french, the real `Download` folder is in fact named `Téléchargement`.

I think could help you to reproduce the issue.

Just try to check a file whose full path is `/home/user/Téléchargement/checklinks/myfile.html`.

**Comment by anarcat** [comment]
On 2018-06-28 07:45:43, oupala wrote:
> Just try to check a file whose full path is `/home/user/Téléchargement/checklinks/myfile.html`.

Je vois! :) In which encoding is the "Téléchargements" folder? I assume
it's in unicode/UTF-8?

thanks! I suspected as much... ;)

**Comment by oupala** [comment]
Yes, my locales are UTF-8.

```bash
>locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```
