### ISSUE TITLE
impossible to check exported bookmarks from Firefox

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#166]
## Summary

I tried to check if my exported bookmarks from Firefox are up to date. Hence I want to check that linkchecker returns no error.

## Steps to reproduce

 1. export your bookmarks from Firefox into an html file
 2. check your exported file by using linkchecker
 3. see that there is an error

## Actual result

many errors (see below)

## Expected result

no error

## Environment

 * Operating system: Debian GNU/Linux 9.4
 * Linkchecker version: LinkChecker 9.3 released 16.7.2014
 * Python version: Python 2.7.13
 * Install method: distribution package
 * Site URL: local file

## Configuration file

no specific configuration file

```
# Sample configuration file; see the linkcheckerrc(5) man page or
# execute linkchecker -h for help on these options.
# Commandline or GUI options override these settings.

##################### output configuration ##########################
[output]
# enable debug messages; see 'linkchecker -h' for valid debug names
#debug=all
# print status output
#status=1
# change the logging type
#log=xml
# turn on/off --verbose
#verbose=1
# turn on/off --warnings
#warnings=0
# turn on/off --quiet
#quiet=1
# additional file output
#fileoutput = text, html, gml, sql


##################### logger configuration ##########################
# Note that the logger configuration is ignored by the linkchecker-gui
# program. Results in the GUI can be saved to a file with the command
# File -> Save results.
#
# logger output part names:
# all       For all parts
# realurl   The full url link
# result    Valid or invalid, with messages
# extern    1 or 0, only in some logger types reported
# base      <base href=...>
# name      <a href=...>name</a> and <img alt="name">
# parenturl The referrer URL if there is any
# info      Some additional info, e.g. FTP welcome messages
# warning   Warnings
# dltime    Download time
# checktime Check time
# url       The original url name, can be relative
# intro     The blurb at the beginning, "starting at ..."
# outro     The blurb at the end, "found x errors ..."
# stats     Statistics including URL lengths and contents.

# each Logger can have separate configuration parameters

# standard text logger
[text]
#filename=linkchecker-out.txt
#parts=all
# colors for the various parts, syntax is <color> or <type>;<color>
# type can be bold, light, blink, invert
# color can be default, black, red, green, yellow, blue, purple, cyan, white,
# Black, Red, Green, Yellow, Blue, Purple, Cyan, White
#colorparent=white
#colorurl=default
#colorname=default
#colorreal=cyan
#colorbase=purple
#colorvalid=bold;green
#colorinvalid=bold;red
#colorinfo=default
#colorwarning=bold;yellow
#colordltime=default
#colorreset=default

# GML logger
[gml]
#filename=linkchecker-out.gml
#parts=all
# valid encodings are listed in http://docs.python.org/library/codecs.html#standard-encodings
# default encoding is iso-8859-15
#encoding=utf_16

# DOT logger
[dot]
#filename=linkchecker-out.dot
#parts=all
# default encoding is ascii since the original DOT format does not
# support other charsets
#encoding=iso-8859-15

# CSV logger
[csv]
#filename=linkchecker-out.csv
#separator=,
#quotechar="
#parts=all

# SQL logger
[sql]
#filename=linkchecker-out.sql
#dbname=linksdb
#separator=;
#parts=all

# HTML logger
[html]
#filename=linkchecker-out.html
# colors for the various parts
#colorbackground=#fff7e5
#colorurl=#dcd5cf
#colorborder=#000000
#colorlink=#191c83
#colorwarning=#e0954e
#colorerror=#db4930
#colorok=#3ba557
#parts=all

# blacklist logger
[blacklist]
#filename=~/.linkchecker/blacklist

# custom xml logger
[xml]
#encoding=iso-8859-1

# GraphXML logger
[gxml]
#encoding=iso-8859-1

# Sitemap logger
[sitemap]
#priority=0.7
#frequency=weekly


##################### checking options ##########################
[checking]
# number of threads
#threads=100
# connection timeout in seconds
#timeout=60
# Time to wait for checks to finish after the user aborts the first time
# (with Ctrl-C or the abort button).
#aborttimeout=300
# The recursion level determines how many times links inside pages are followed.
#recursionlevel=1
# Basic NNTP server. Overrides NNTP_SERVER environment variable.
#nntpserver=
# parse a cookiefile for initial cookie data
#cookiefile=/path/to/cookies.txt
# User-Agent header string to send to HTTP web servers
# Note that robots.txt are always checked with the original User-Agent.
#useragent=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
# When checking finishes, write a memory dump to a temporary file.
# The memory dump is written both when checking finishes normally
# and when checking gets canceled.
# The memory dump only works if the python-meliae package is installed.
# Otherwise a warning is printed to install it.
#debugmemory=0
# When checking absolute URLs inside local files, the given root directory
# is used as base URL.
# Note that the given directory must have URL syntax, so it must use a slash
# to join directories instead of a backslash.
# And the given directory must end with a slash.
# Unix example:
#localwebroot=/var/www/
# Windows example:
#localwebroot=/C|/public_html/
# Check SSL certificates. Set to an absolute pathname for a custom
# CA cert bundle to use. Set to zero to disable SSL certificate verification.
#sslverify=1
# Stop checking new URLs after the given number of seconds. Same as if the
# user hits Ctrl-C after X seconds.
#maxrunseconds=600
# Maximum number of URLs to check. New URLs will not be queued after the
# given number of URLs is checked.
#maxnumurls=153
# Maximum number of requests per second to one host.
#maxrequestspersecond=10
# Allowed URL schemes as a comma-separated list.
#allowedschemes=http,https

##################### filtering options ##########################
[filtering]
#ignore=
# ignore everything with 'lconline' in the URL name
#  lconline
# and ignore everything with 'bookmark' in the URL name
#  bookmark
# and ignore all mailto: URLs
#  ^mailto:
# do not recurse into the following URLs

#nofollow=
# just an example
#  http://www\.example\.com/bla

# Ignore specified warnings (see linkchecker -h for the list of
# recognized warnings). Add a comma-separated list of warnings here
# that prevent a valid URL from being logged. Note that the warning
# will be logged in invalid URLs.
#ignorewarnings=url-unicode-domain
# Regular expression to add more URLs recognized as internal links.
# Default is that URLs given on the command line are internal.
#internlinks=^http://www\.example\.net/
# Check external links
#checkextern=1


##################### password authentication ##########################
[authentication]
# WARNING: if you store passwords in this configuration entry, make sure the
# configuration file is not readable by other users.
# Different user/password pairs for different URLs can be provided.
# Entries are a triple (URL regular expression, username, password),
# separated by whitespace.
# If the regular expression matches, the given user/password pair is used
# for authentication. The commandline options -u,-p match every link
# and therefore override the entries given here. The first match wins.
# At the moment, authentication is used for http[s] and ftp links.
#entry=
# Note that passwords are optional. If any passwords are stored here,
# this file should not readable by other users.
#  ^https?://www\.example\.com/~calvin/ calvin mypass
#  ^ftp://www\.example\.com/secret/ calvin

# if the website requires a login the URL and optionally the user and
# password CGI fieldnames can be provided.
#loginurl=http://www.example.com/

# The name of the user and password CGI field
#loginuserfield=login
#loginpasswordfield=password
# Optionally any additional CGI name/value pairs. Note that the default
# values are submitted automatically.
#loginextrafields=
#  name1:value1
#  name 2:value 2

############################ Plugins ###################################
#
# uncomment sections to enable plugins

# Check HTML anchors
#[AnchorCheck]

# Print HTTP header info
#[HttpHeaderInfo]
# Comma separated list of header prefixes to print.
# The names are case insensitive.
# The default list is empty, so it should be non-empty when activating
# this plugin.
#prefixes=Server,X-

# Add country info to URLs
#[LocationInfo]

# Run W3C syntax checks
#[CssSyntaxCheck]
#[HtmlSyntaxCheck]

# Search for regular expression in page contents
#[RegexCheck]
#warningregex=Oracle Error

# Search for viruses in page contents
#[VirusCheck]
#clamavconf=/etc/clamav/clam.conf

# Check that SSL certificates are at least the given number of days valid.
#[SslCertificateCheck]
#sslcertwarndays=14

# Parse and check links in PDF files
#[PdfParser]

# Parse and check links in Word files
#[WordParser]
```

## Logs

```log
>linkchecker -Dall --file-output=html --check-extern myfile.html  
DEBUG 2018-06-28 18:12:52,719 MainThread Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
DEBUG 2018-06-28 18:12:52,719 MainThread reading configuration from ['/home/user/.linkchecker/linkcheckerrc']
DEBUG 2018-06-28 18:12:52,728 MainThread configuration: [('aborttimeout', 300),
 ('allowedschemes', []),
 ('authentication', []),
 ('blacklist', {}),
 ('checkextern', True),
 ('cookiefile', None),
 ('csv', {}),
 ('debugmemory', False),
 ('dot', {}),
 ('enabledplugins', []),
 ('externlinks', []),
 ('fileoutput', ['HtmlLogger']),
 ('gml', {}),
 ('gxml', {}),
 ('html', {'fileoutput': 1}),
 ('ignorewarnings', []),
 ('internlinks', []),
 ('localwebroot', None),
 ('logger', 'TextLogger'),
 ('loginextrafields', {}),
 ('loginpasswordfield', 'password'),
 ('loginurl', None),
 ('loginuserfield', 'login'),
 ('maxfilesizedownload', 5242880),
 ('maxfilesizeparse', 1048576),
 ('maxhttpredirects', 10),
 ('maxnumurls', None),
 ('maxrequestspersecond', 10),
 ('maxrunseconds', None),
 ('nntpserver', None),
 ('none', {}),
 ('output', 'text'),
 ('pluginfolders', []),
 ('proxy',
  {'http': 'http://proxy:8080/',
   'https': 'http://proxy:8080/',
 ('quiet', False),
 ('recursionlevel', -1),
 ('sitemap', {}),
 ('sql', {}),
 ('sslverify', True),
 ('status', True),
 ('status_wait_seconds', 5),
 ('text', {}),
 ('threads', 10),
 ('timeout', 60),
 ('trace', False),
 ('useragent',
  u'Mozilla/5.0 (compatible; LinkChecker/9.3; +http://wummel.github.io/linkchecker/)'),
 ('verbose', False),
 ('warnings', True),
 ('xml', {})]
DEBUG 2018-06-28 18:12:52,729 MainThread FileUrl handles url myfile.html
DEBUG 2018-06-28 18:12:52,729 MainThread checking syntax
DEBUG 2018-06-28 18:12:52,729 MainThread Add intern pattern u'file\\:\\/\\/\\/home\\/user\\/checklinks\\/'
DEBUG 2018-06-28 18:12:52,729 MainThread Link pattern u'file\\:\\/\\/\\/home\\/user\\/checklinks\\/' strict=False
DEBUG 2018-06-28 18:12:52,729 MainThread queueing file:///home/user/checklinks/myfile.html
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2018-06-28 18:12:52+002
DEBUG 2018-06-28 18:12:52,733 CheckThread-file:///home/user/checklinks/myfile.html Checking file link
base_url=u'file:///home/user/checklinks/myfile.html'
parent_url=None
base_ref=None
recursion_level=0
url_connection=None
line=0
column=0
page=0
name=u'myfile.html'
anchor=u''
cache_url=file:///home/user/checklinks/myfile.html
DEBUG 2018-06-28 18:12:52,735 CheckThread-file:///home/user/checklinks/myfile.html checking connection
DEBUG 2018-06-28 18:12:52,736 CheckThread-file:///home/user/checklinks/myfile.html checking recursion of u'file:///home/user/checklinks/myfile.html' ...
DEBUG 2018-06-28 18:12:52,736 CheckThread-file:///home/user/checklinks/myfile.html ... yes, recursion.
DEBUG 2018-06-28 18:12:52,736 CheckThread-file:///home/user/checklinks/myfile.html Get content of u'file:///home/user/checklinks/myfile.html'
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag meta attrs {u'http-equiv': u'Content-Type', u'content': u'text/html; charset=UTF-8'}
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html line 5 col 68 old line 5 old col 1
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag meta
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag title attrs {}
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html line 6 col 8 old line 6 old col 1
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag title
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag h1 attrs {}
DEBUG 2018-06-28 18:12:52,737 CheckThread-file:///home/user/checklinks/myfile.html line 7 col 5 old line 7 old col 1
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag h1
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dl attrs {}
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html line 9 col 5 old line 9 old col 1
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dl
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag p attrs {}
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html line 9 col 8 old line 9 old col 5
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag p
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag hr attrs {}
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html line 10 col 9 old line 10 old col 5
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag hr
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dt attrs {}
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html line 10 col 17 old line 10 old col 13
DEBUG 2018-06-28 18:12:52,738 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dt
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag h3 attrs {u'add_date': u'1092754607', u'last_modified': u'1530089278'}
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html line 10 col 70 old line 10 old col 17
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag h3
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dl attrs {}
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html line 11 col 9 old line 11 old col 5
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dl
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag p attrs {}
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html line 11 col 12 old line 11 old col 9
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag p
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dt attrs {}
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html line 12 col 13 old line 12 old col 9
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dt
DEBUG 2018-06-28 18:12:52,739 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag h3 attrs {u'add_date': u'1470050906', u'last_modified': u'1504856319'}
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html line 12 col 66 old line 12 old col 13
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag h3
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dl attrs {}
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html line 13 col 13 old line 13 old col 9
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dl
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag p attrs {}
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html line 13 col 16 old line 13 old col 13
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag p
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag dt attrs {}
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html line 14 col 17 old line 14 old col 13
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag dt
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag a attrs {u'last_charset': u'UTF-8', u'tags': u'tech,git', u'last_modified': u'1469789296', u'add_date': u'1469789287', u'href': u'http://marklodato.github.io/visual-git-guide/index-en.html'}
DEBUG 2018-06-28 18:12:52,740 CheckThread-file:///home/user/checklinks/myfile.html line 14 col 172 old line 14 old col 17
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html HttpUrl handles url http://marklodato.github.io/visual-git-guide/index-en.html
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html checking syntax
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html queueing http://marklodato.github.io/visual-git-guide/index-en.html
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag a
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag p attrs {}
DEBUG 2018-06-28 18:12:52,741 CheckThread-file:///home/user/checklinks/myfile.html line 15 col 17 old line 15 old col 14
DEBUG 2018-06-28 18:12:52,742 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag p
DEBUG 2018-06-28 18:12:52,742 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder tag p attrs {}
DEBUG 2018-06-28 18:12:52,742 CheckThread-file:///home/user/checklinks/myfile.html line 16 col 13 old line 16 old col 10
DEBUG 2018-06-28 18:12:52,742 CheckThread-file:///home/user/checklinks/myfile.html LinkFinder finished tag p
DEBUG 2018-06-28 18:12:52,742 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html Checking http link
base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html'
parent_url=u'file:///home/user/checklinks/myfile.html'
base_ref=None
recursion_level=1
url_connection=None
line=14
column=17
page=0
name=u'a visual git reference'
anchor=u''
cache_url=http://marklodato.github.io/visual-git-guide/index-en.html
DEBUG 2018-06-28 18:12:52,743 CheckThread-file:///home/user/checklinks/myfile.html task_done file:///home/user/checklinks/myfile.html
DEBUG 2018-06-28 18:12:52,743 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html checking connection
DEBUG 2018-06-28 18:12:52,745 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html using proxy 'proxy:8080'
DEBUG 2018-06-28 18:12:52,745 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html task_done http://marklodato.github.io/visual-git-guide/index-en.html


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html, started 140529420302080)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html, started 140529420302080)>>
      url_data = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fcf8f4f32a8>
      url_data = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      self = <local> <Checker(CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html, started 140529420302080)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fcf8ee072d0>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      url_data.check = <local> <bound method HttpUrl.check of <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      self.local_check = <local> <bound method HttpUrl.local_check of <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', a...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      self.check_connection = <local> <bound method HttpUrl.check_connection of <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git referenc...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 128, in check_connection
    line: if not self.allows_robots(self.url):
    locals:
      self = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      self.allows_robots = <local> <bound method HttpUrl.allows_robots of <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference',...
      self.url = <local> u'http://marklodato.github.io/visual-git-guide/index-en.html', len = 58
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 66, in allows_robots
    line: return self.aggregate.robots_txt.allows_url(self)
    locals:
      self = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      self.aggregate = <local> <linkcheck.director.aggregator.Aggregate object at 0x7fcf8ee07250>
      self.aggregate.robots_txt = <local> <linkcheck.cache.robots_txt.RobotsTxt object at 0x7fcf8ee071d0>
      self.aggregate.robots_txt.allows_url = <local> <bound method RobotsTxt.allows_url of <linkcheck.cache.robots_txt.RobotsTxt object at 0x7fcf8ee071d0>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/cache/robots_txt.py", line 49, in allows_url
    line: return self._allows_url(url_data, roboturl)
    locals:
      self = <local> <linkcheck.cache.robots_txt.RobotsTxt object at 0x7fcf8ee071d0>
      self._allows_url = <local> <bound method RobotsTxt._allows_url of <linkcheck.cache.robots_txt.RobotsTxt object at 0x7fcf8ee071d0>>
      url_data = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      roboturl = <local> u'http://marklodato.github.io/robots.txt', len = 38
  File "/usr/lib/python2.7/dist-packages/linkcheck/cache/robots_txt.py", line 62, in _allows_url
    line: kwargs["proxies"] = {url_data.proxy_type, url_data.proxy}
    locals:
      kwargs = <local> {'auth': None, 'session': <requests.sessions.Session object at 0x7fcf8ee07450>}
      url_data = <local> <http link, base_url=u'http://marklodato.github.io/visual-git-guide/index-en.html', parent_url=u'file:///home/user/checklinks/myfile.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=17, page=0, name=u'a visual git reference', anchor=u'', cache_url=http://marklodat...
      url_data.proxy_type = <local> !AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
      url_data.proxy = <local> 'proxy:8080', len = 10
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Requests: 2.12.4
Modules: Sqlite
Local time: 2018-06-28 18:12:52+002
sys.argv: ['/usr/bin/linkchecker', '-Dall', '--file-output=html', '--check-extern', 'myfile.html']
http_proxy = 'http://proxy:8080/'
no_proxy = 'localhost,127.0.0.0/8,::1,.intraorange,.francetelecom.fr,.ftgroup,.orange-labs.fr'
LANG = 'fr_FR.UTF-8'
Default locale: ('fr', 'UTF-8')

 ******** LinkChecker internal error, over and out ********

Statistics:
Downloaded: 689B.
WARNING 2018-06-28 18:12:52,748 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html internal error occurredContent types: 0 image, 1 text, 0 video, 0 audio, 0 application, 0 mail and 0 other.
URL lengths: min=44, max=44, avg=44.


That's it. WARNING 2018-06-28 18:12:52,749 CheckThread-http://marklodato.github.io/visual-git-guide/index-en.html internal error occurred1 link 
in 1 URL checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2018-06-28 18:12:52+002 (0.02 seconds)
```

## Other notes

Maybe this could be due to the proxy settings.

**Comment by anarcat** [comment]
This issue was already reported in #152 - thanks for the confirmation!
