### ISSUE TITLE
Unable to `sudo pip install linkchecker` on Arch Linux

### ISSUE THREAD

**Issue by Compro-Prasad** [linkchecker/linkchecker#171]
```
20:48 : linkchecker $ sudo pip install linkchecker
Collecting linkchecker
  Using cached https://files.pythonhosted.org/packages/43/59/31baf302792306bde0825e8631a74c7f668bc47b3748fc4471c281885bb6/LinkChecker-9.3.tar.gz
Requirement already satisfied: requests>=2.2.0 in /usr/lib/python3.6/site-packages (from linkchecker) (2.19.1)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->linkchecker) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->linkchecker) (2.7)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.2.0->linkchecker) (1.23)
Building wheels for collected packages: linkchecker
  Running setup.py bdist_wheel for linkchecker ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9nqafs6j/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-z1adnc2b --python-tag cp36:
  creating /tmp/pip-install-9nqafs6j/linkchecker/_LinkChecker_configdata.py
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 976, in <module>
      setup(**args)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 476, in run_commands
      super(MyDistribution, self).run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 602, in run
      self.build_message_files()
    File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 592, in build_message_files
      import msgfmt
    File "po/msgfmt.py", line 82
      0x950412deL,       # Magic
                ^
  SyntaxError: invalid syntax
  
  ----------------------------------------
  Failed building wheel for linkchecker
  Running setup.py clean for linkchecker
Failed to build linkchecker
tensorflow-tensorboard 0.4.0rc3 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
bleach 1.5.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999, but you'll have html5lib 1.0.1 which is incompatible.
Installing collected packages: linkchecker
  Running setup.py install for linkchecker ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9nqafs6j/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1mjjx6ng/install-record.txt --single-version-externally-managed --compile:
    creating /tmp/pip-install-9nqafs6j/linkchecker/_LinkChecker_configdata.py
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 976, in <module>
        setup(**args)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 476, in run_commands
        super(MyDistribution, self).run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 602, in run
        self.build_message_files()
      File "/tmp/pip-install-9nqafs6j/linkchecker/setup.py", line 592, in build_message_files
        import msgfmt
      File "po/msgfmt.py", line 82
        0x950412deL,       # Magic
                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9nqafs6j/linkchecker/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1mjjx6ng/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-9nqafs6j/linkchecker/
```

**Comment by mgedmin** [comment]
linkchecker doesn't support Python 3 yet, see issue #40.

Famously, /usr/bin/python is Python 3 on ArchLinux, but Python 2 on most (all?) other Linux distributions.

**Comment by Compro-Prasad** [comment]
I installed now with `pip2` and its fine now. But it needs `>requests2.2.0` but I have 2.19.1

**Comment by mgedmin** [comment]
The version of linkchecker on PyPI is outdated and buggy, and we cannot update it yet due to the original maintainer missing in action (see #4).  

For now you can try `pip2 install git+https://github.com/linkchecker/linkchecker`

**Comment by Compro-Prasad** [comment]
Do mention this in the README.
