### ISSUE TITLE
Internal error on trailing comma in srcset

### ISSUE THREAD

**Issue by figaw** [linkchecker/linkchecker#173]
## Summary

linkchecker reports internal error on trailing comma in an `img`-`srcset` attribute.
- from the specification it's clearly a violation, but the linkchecker should probably fail more gracefully and just report it as an error/warning.

## Steps to reproduce

 1. Create a file `test.png` and an `index.html` file beside it with the following contents,
```
<html>
<body>
    <img src="test.png"/ srcset="test.png 200w,">
</body>
</html>
```
 2. Run the linkchecker. I'm running it through the docker-container, like so
```
$ docker run --rm -v "$PWD":/mnt linkchecker/linkchecker:latest index.html \
    --verbose -Dall > output.txt 2> debug.txt
```
 3. `debug.txt` contains the error

## Actual result

Internal error.

## Expected result

A warning or error found. (It's breaking specs but renders without trouble in a browser, so you'll have to decide the level of seriousness. I'd probably go with warning.)

## Environment
Running it in WSL on Windows 10, but the above "should be" completely reproducible on any environment. My colleague ran the image on a mac, with the same result. Our Linux-Jenkins machine does exactly the same when it checks our corporate website ( - I was able to drill down to the core-example above)

 * Operating system: Linux DESKTOP-7OMIIA2 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
 * Linkchecker version: LinkChecker 9.4.0 released xx.xx.xxxx
 * Python version: linkchecker/linkchecker:latest - you should probably tag these.. it looks like Python 2 in the Dockerfile.
 * Install method: docker-image
 * Site URL: not applicable

## Configuration file

linkchecker/linkchecker:latest

## Logs

output.txt
```
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2018-07-19 11:00:47+000

URL        `test.png'
Parent URL file:///mnt/index.html, line 3, col 5
Real URL   file:///mnt/test.png
Check time 0.002 seconds
Size       0B
Modified   2018-07-19 10:57:36.208000Z
Result     Valid

Statistics:
Downloaded: 85B.
Content types: 1 image, 0 text, 0 video, 0 audio, 0 application, 0 mail and 0 other.
URL lengths: min=20, max=20, avg=20.

That's it. 1 link in 2 URLs checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2018-07-19 11:00:47+000 (0.04 seconds)
```

debug.txt
```
DEBUG linkcheck.cmdline 2018-07-19 11:00:47,387 MainThread Python 2.7.14 (default, Mar 14 2018, 18:21:57) 
[GCC 4.9.2] on linux2
DEBUG linkcheck.check 2018-07-19 11:00:47,388 MainThread reading configuration from ['/tmp/.config/linkchecker/linkcheckerrc']
WARNING linkcheck.check 2018-07-19 11:00:47,406 MainThread Running as root user; dropping privileges by changing user to nobody.
INFO linkcheck.cmdline 2018-07-19 11:00:47,407 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
DEBUG linkcheck.cmdline 2018-07-19 11:00:47,410 MainThread configuration: [('aborttimeout', 300),
 ('allowedschemes', []),
 ('authentication', []),
 ('blacklist', {}),
 ('checkextern', False),
 ('cookiefile', None),
 ('csv', {}),
 ('debugmemory', False),
 ('dot', {}),
 ('enabledplugins', []),
 ('externlinks', []),
 ('fileoutput', []),
 ('gml', {}),
 ('gxml', {}),
 ('html', {}),
 ('ignorewarnings', []),
 ('internlinks', []),
 ('localwebroot', None),
 ('logger', 'TextLogger'),
 ('loginextrafields', {}),
 ('loginpasswordfield', 'password'),
 ('loginurl', None),
 ('loginuserfield', 'login'),
 ('maxfilesizedownload', 5242880),
 ('maxfilesizeparse', 1048576),
 ('maxhttpredirects', 10),
 ('maxnumurls', None),
 ('maxrequestspersecond', 10),
 ('maxrunseconds', None),
 ('nntpserver', None),
 ('none', {}),
 ('output', 'text'),
 ('pluginfolders', []),
 ('proxy', {}),
 ('quiet', False),
 ('recursionlevel', -1),
 ('robotstxt', True),
 ('sitemap', {}),
 ('sql', {}),
 ('sslverify', '/etc/ssl/certs/ca-certificates.crt'),
 ('status', True),
 ('status_wait_seconds', 5),
 ('text', {}),
 ('threads', 10),
 ('timeout', 60),
 ('trace', False),
 ('useragent',
  u'Mozilla/5.0 (compatible; LinkChecker/9.4.0; +http://wummel.github.io/linkchecker/)'),
 ('verbose', True),
 ('warnings', True),
 ('xml', {})]
DEBUG linkcheck.check 2018-07-19 11:00:47,411 MainThread FileUrl handles url index.html
DEBUG linkcheck.check 2018-07-19 11:00:47,411 MainThread checking syntax
DEBUG linkcheck.check 2018-07-19 11:00:47,414 MainThread Add intern pattern u'file\\:\\/\\/\\/mnt\\/'
DEBUG linkcheck.check 2018-07-19 11:00:47,414 MainThread Link pattern u'file\\:\\/\\/\\/mnt\\/' strict=False
DEBUG linkcheck.cache 2018-07-19 11:00:47,414 MainThread queueing file:///mnt/index.html
DEBUG linkcheck.check 2018-07-19 11:00:47,418 CheckThread-file:///mnt/index.html Checking file link
base_url=u'file:///mnt/index.html'
parent_url=None
base_ref=None
recursion_level=0
url_connection=None
line=0
column=0
page=0
name=u'index.html'
anchor=u''
cache_url=file:///mnt/index.html
DEBUG linkcheck.check 2018-07-19 11:00:47,421 CheckThread-file:///mnt/index.html checking connection
DEBUG linkcheck.check 2018-07-19 11:00:47,424 CheckThread-file:///mnt/index.html checking recursion of u'file:///mnt/index.html' ...
DEBUG linkcheck.check 2018-07-19 11:00:47,424 CheckThread-file:///mnt/index.html ... yes, recursion.
DEBUG linkcheck.check 2018-07-19 11:00:47,425 CheckThread-file:///mnt/index.html Get content of u'file:///mnt/index.html'
DEBUG linkcheck.check 2018-07-19 11:00:47,426 CheckThread-file:///mnt/index.html LinkFinder tag html attrs {}
DEBUG linkcheck.check 2018-07-19 11:00:47,427 CheckThread-file:///mnt/index.html line 1 col 7 old line 1 old col 1
DEBUG linkcheck.check 2018-07-19 11:00:47,427 CheckThread-file:///mnt/index.html LinkFinder finished tag html
DEBUG linkcheck.check 2018-07-19 11:00:47,428 CheckThread-file:///mnt/index.html LinkFinder tag body attrs {}
DEBUG linkcheck.check 2018-07-19 11:00:47,428 CheckThread-file:///mnt/index.html line 2 col 7 old line 2 old col 1
DEBUG linkcheck.check 2018-07-19 11:00:47,429 CheckThread-file:///mnt/index.html LinkFinder finished tag body
DEBUG linkcheck.check 2018-07-19 11:00:47,429 CheckThread-file:///mnt/index.html LinkFinder tag img attrs {u'srcset': u'test.png 200w,', u'src': u'test.png'}
DEBUG linkcheck.check 2018-07-19 11:00:47,429 CheckThread-file:///mnt/index.html line 3 col 50 old line 3 old col 5
DEBUG linkcheck.check 2018-07-19 11:00:47,429 CheckThread-file:///mnt/index.html FileUrl handles url test.png
DEBUG linkcheck.check 2018-07-19 11:00:47,429 CheckThread-file:///mnt/index.html checking syntax
DEBUG linkcheck.check 2018-07-19 11:00:47,430 CheckThread-file:///mnt/index.html Intern URL u'file:///mnt/test.png'
DEBUG linkcheck.cache 2018-07-19 11:00:47,431 CheckThread-file:///mnt/index.html queueing file:///mnt/test.png
DEBUG linkcheck.check 2018-07-19 11:00:47,431 CheckThread-file:///mnt/index.html FileUrl handles url test.png
DEBUG linkcheck.check 2018-07-19 11:00:47,431 CheckThread-file:///mnt/index.html checking syntax
DEBUG linkcheck.check 2018-07-19 11:00:47,431 CheckThread-file:///mnt/index.html Intern URL u'file:///mnt/test.png'
DEBUG linkcheck.cache 2018-07-19 11:00:47,431 CheckThread-file:///mnt/index.html queueing file:///mnt/test.png
DEBUG linkcheck.cache 2018-07-19 11:00:47,432 CheckThread-file:///mnt/index.html task_done file:///mnt/index.html


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-file:///mnt/index.html, started 140284689450752)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-file:///mnt/index.html, started 140284689450752)>>
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f9695099a28>
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
      self = <local> <Checker(CheckThread-file:///mnt/index.html, started 140284689450752)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f9695c40150>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x7f9695099050>
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 41, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 50, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x7f9695099488>
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
      url_data.add_url = <local> <bound method FileUrl.add_url of <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>>
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'source': [u'src'], 'head': [u'profile'], None: [u'style', u'itemtype'], 'th': [u'background'], 'ins': [u'cite'], 'td': [u'background'], 'html': [u'manifest'], 'q': [u'cite'], 'form': [u'action'], 'area': [u'href'], 'embed': [u'pluginspage', u'src'], 'audio': [u'src'], 'a': [u'href'], 'meta': [u..., len = 35
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 128, in find_links
    line: parser.feed(url_data.get_content())
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7f9695c3b730>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7f9695c3b730>
      url_data = <local> <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>
      url_data.get_content = <local> <bound method FileUrl.get_content of <file link, base_url=u'file:///mnt/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'index.html', anchor=u'', cache_url=file:///mnt/index.html>>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7f9695a64190>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7f9695a64190>>
      tag = <local> u'img'
      attr = <local> u'srcset', len = 6
      value = <local> u'test.png 200w,', len = 14
      name = <local> u''
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 274, in parse_tag
    line: url = img_candidate.split()[0]
    locals:
      url = <local> u'test.png', len = 8
      img_candidate = <local> u''
      img_candidate.split = <local> <built-in method split of unicode object at 0x7f969c77f180>
IndexError: list index out of range
System info:
LinkChecker 9.4.0
Released on: xx.xx.xxxx
Python 2.7.14 (default, Mar 14 2018, 18:21:57) 
[GCC 4.9.2] on linux2
Modules: Requests, Pysqlite, Sqlite
DEBUG linkcheck.check 2018-07-19 11:00:47,435 CheckThread-file:///mnt/test.png Checking file link
base_url=u'test.png'
parent_url=u'file:///mnt/index.html'
base_ref=None
recursion_level=1
url_connection=None
line=3
column=5
page=0
name=u''
anchor=u''
cache_url=file:///mnt/test.png
DEBUG linkcheck.check 2018-07-19 11:00:47,435 CheckThread-file:///mnt/test.png checking connection
Local time: 2018-07-19 11:00:47+000
sys.argv: ['/usr/local/bin/linkchecker', 'index.html', '--verbose', '-Dall']
LANG = 'C.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2018-07-19 11:00:47,436 CheckThread-file:///mnt/index.html internal error occurred
DEBUG linkcheck.check 2018-07-19 11:00:47,436 CheckThread-file:///mnt/test.png checking recursion of u'file:///mnt/test.png' ...
DEBUG linkcheck.check 2018-07-19 11:00:47,437 CheckThread-file:///mnt/test.png File with content type 'image/png' is not parseable.
DEBUG linkcheck.check 2018-07-19 11:00:47,437 CheckThread-file:///mnt/test.png ... no, not parseable.
DEBUG linkcheck.cache 2018-07-19 11:00:47,438 CheckThread-file:///mnt/test.png task_done file:///mnt/test.png
```

**Comment by cjmayo** [comment]
I've included a fix for this in #474
