### ISSUE TITLE
internal error in command line

### ISSUE THREAD

**Issue by nledl** [linkchecker/linkchecker#182]
## Summary

<linkchecker reports internal error, doesn't finish the process, no output of broken links>

## Steps to reproduce

 1. URL: www.digitale-sammlungen.de
 2. command line: linkchecker www.digitale-sammlungen.de

## Actual result
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://www.digitale-sammlungen.de/index.html?c=autoren_index&l=de&ab=Stryk,%20Samuel&l=de, started 139832738985728)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://www.digitale-sammlungen.de/index.html?c=autoren_index&l=de&ab=Stryk,%20Samuel&l=de, started 139832738985728)>>
      url_data = <local> <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'1.248', anchor=u'', cache_url=https://www....
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f2d59acd6e0>
      url_data = <local> <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'1.248', anchor=u'', cache_url=https://www....
      self = <local> <Checker(CheckThread-https://www.digitale-sammlungen.de/index.html?c=autoren_index&l=de&ab=Stryk,%20Samuel&l=de, started 139832738985728)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f2d593e8850>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 53, in check_url
    line: do_parse = url_data.check_content()
    locals:
      do_parse = <not found>
      url_data = <local> <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'1.248', anchor=u'', cache_url=https://www....
      url_data.check_content = <local> <bound method HttpUrl.check_content of <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'1.2...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 468, in check_content
    line: value = self.handle_exception()
    locals:
      value = <not found>
      self = <local> <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'1.248', anchor=u'', cache_url=https://www....
      self.handle_exception = <local> <bound method HttpUrl.handle_exception of <https link, base_url=u'index.html?c=autoren_index&l=de&ab=Stryk%2C+Samuel&l=de', parent_url=u'https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de', base_ref=None, recursion_level=2, url_connection=None, line=77, column=29515, page=0, name=u'...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 501, in handle_exception
    line: uvalue = strformat.unicode_safe(evalue)
    locals:
      uvalue = <not found>
      strformat = <global> <module 'linkcheck.strformat' from '/usr/lib/python2.7/dist-packages/linkcheck/strformat.pyc'>
      strformat.unicode_safe = <global> <function unicode_safe at 0x7f2d5a58e320>
      evalue = <local> LinkCheckerError(u'Dateigr\xf6\xdfe ist zu gro\xdf',), _[0]: {len = 22}
  File "/usr/lib/python2.7/dist-packages/linkcheck/strformat.py", line 56, in unicode_safe
    line: return unicode(str(s), encoding, errors)
    locals:
      unicode = <builtin> <type 'unicode'>
      str = <builtin> <type 'str'>
      s = <local> LinkCheckerError(u'Dateigr\xf6\xdfe ist zu gro\xdf',), _[0]: {len = 22}
      encoding = <local> 'UTF-8'
      errors = <local> 'replace', len = 7
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)
Systeminformation:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] auf linux2
Requests: 2.9.1
Modules: Sqlite
Uhrzeit: 2018-08-10 08:39:09+002
sys.argv: ['/usr/bin/linkchecker', 'www.digitale-sammlungen.de', '--ignore-url=^www.digitale-sammlunge.de/index.html?c=autoren*']
LANGUAGE = 'de_DE'
LANG = 'de_DE.UTF-8'
Standard Locale: ('de', 'UTF-8')
Getötet

## Expected result
list of broken links

## Environment
system information:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] auf linux2
Requests: 2.9.1
Modules: Sqlite
Uhrzeit: 2018-08-10 08:39:09+002
sys.argv: ['/usr/bin/linkchecker', 'www.digitale-sammlungen.de', '--ignore-url=^www.digitale-sammlunge.de/index.html?c=autoren*']
LANGUAGE = 'de_DE'
LANG = 'de_DE.UTF-8'
Standard Locale: ('de', 'UTF-8')

## Configuration file
linkchecker-9.3.tar.gz

**Comment by anarcat** [comment]
can you try with the latest version?

    pip install git+https://github.com/linkchecker/linkchecker.git

**Comment by nledl** [comment]
installed version 9.4.0
result now:
URL        `index.html?c=autoren_index&l=de&ab=Calov%2C+Abraham&l=de'
Name       ` Abraham Calov  (274)'
Parent URL https://www.digitale-sammlungen.de/index.html?c=statistiken&l=de, line 77, col 84612
Real URL   https://www.digitale-sammlungen.de/index.html?c=autoren_index&l=de&ab=Calov,%20Abraham&l=de
Check time 0.528 seconds
Warning    [url-error-getting-content] could not get content:
           LinkCheckerError: File size too large
Result     Valid: 200 OK
10 threads active, 47908 links queued, 5188 links in 53107 URLs checked, runtime 11 minutes, 12 seconds
10 threads active, 47910 links queued, 5188 links in 53109 URLs checked, runtime 11 minutes, 17 seconds
10 threads active, 47911 links queued, 5188 links in 53110 URLs checked, runtime 11 minutes, 22 seconds
10 threads active, 47911 links queued, 5188 links in 53110 URLs checked, runtime 11 minutes, 27 seconds
10 threads active, 47912 links queued, 5188 links in 53111 URLs checked, runtime 11 minutes, 32 seconds
10 threads active, 47912 links queued, 5188 links in 53111 URLs checked, runtime 11 minutes, 37 seconds
10 threads active, 47912 links queued, 5188 links in 53111 URLs checked, runtime 11 minutes, 42 seconds
10 threads active, 47912 links queued, 5188 links in 53111 URLs checked, runtime 11 minutes, 47 seconds
10 threads active, 47912 links queued, 5188 links in 53111 URLs checked, runtime 11 minutes, 52 seconds
10 threads active, 47967 links queued, 5188 links in 53166 URLs checked, runtime 11 minutes, 58 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 3 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 8 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 13 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 20 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 29 seconds
10 threads active, 47980 links queued, 5188 links in 53179 URLs checked, runtime 12 minutes, 45 seconds
10 threads active, 47942 links queued, 5229 links in 53182 URLs checked, runtime 12 minutes, 52 seconds
10 threads active, 47942 links queued, 5229 links in 53182 URLs checked, runtime 12 minutes, 58 seconds
10 threads active, 47942 links queued, 5229 links in 53182 URLs checked, runtime 13 minutes, 5 seconds
10 threads active, 47942 links queued, 5229 links in 53182 URLs checked, runtime 13 minutes, 10 seconds
10 threads active, 47942 links queued, 5229 links in 53182 URLs checked, runtime 13 minutes, 18 seconds
Getötet

Unfortunately still nor running till the end
