### ISSUE TITLE
Error: TooManyRedirects: Exceeded 10 redirects.

### ISSUE THREAD

**Issue by sachinbanugariya** [linkchecker/linkchecker#199]
hello,
i used linkchecker from many times, its working well,
but suddenly now its giving 
Error: TooManyRedirects: Exceeded 10 redirects. errors.

can you please give me the solution for this,
or parameter for increase the redirect values in linkchecker.
thanks

**Comment by mgedmin** [comment]
That to me looks like a website problem (redirect loop).  You can verify by testing the same URL in a web browser.

**Comment by sachinbanugariya** [comment]
website is working fine.

**Comment by anarcat** [comment]
i'm sorry, but that won't do. :) you need to at least tell us which site is causing problems. you obviously removed the issue template when you filed this issue, which is a little rude. i spent time creating that template, the least you could do would be to fill it up.

here's a copy, again, in case you lost it:

**Comment by reinholdfuereder** [comment]
I stumbled over this problem (with linkchecker version from ~March 2019 on Ubuntu 18.04 Docker image) as well now and have the naive feeling it could be because of lack of support for new  protocols (TLS 1.2?) due to debug log (at the bottom of this message: "_cannot extract SSL certificate from connection_"):
```
03:34:18  URL        `http://www.wirecard.at'
03:34:18  Name       `WIRECARD'
03:34:18  Parent URL https://www.fahnen-gaertner.com/de/shop/zahlungskonditionen.html, line 737, col 145
03:34:18  Real URL   https://www.wirecard.at/
03:34:18  Check time 0.548 seconds
03:34:18  Size       232B
03:34:18  Info       Redirected to `https://www.wirecard.at/'.
03:34:18  Result     Error: TooManyRedirects: Exceeded 10 redirects.
```

Website (3rd party) looks IMHO fine:
* certificate on the website is allegedly installed on 15.01.2020
  * I am though not sure if we were testing this in the past
* https://www.ssllabs.com/ssltest/analyze.html?d=www.wirecard.at&s=13.227.73.113&latest => Grade A?
  * duplicate HSTS header should be irrelevant, I guess?

And debug log shows:
```
root@850de44c0ef8:/# linkchecker --debug=all --threads=2 --recursion-level=0 --no-warnings --no-status --check-extern https://www.wirecard.at/
DEBUG linkcheck.cmdline 2020-05-13 10:23:27,275 MainThread Python 2.7.17 (default, Apr 15 2020, 17:20:14)
[GCC 7.5.0] on linux2
DEBUG linkcheck.check 2020-05-13 10:23:27,275 MainThread reading configuration from []
WARNING linkcheck.check 2020-05-13 10:23:27,281 MainThread Running as root user; dropping privileges by changing user to nobody.
DEBUG linkcheck.cmdline 2020-05-13 10:23:27,283 MainThread configuration: [('aborttimeout', 300),
('allowedschemes', []),
('authentication', []),
('blacklist', {}),
('checkextern', True),
('cookiefile', None),
('csv', {}),
('debugmemory', False),
('dot', {}),
('enabledplugins', []),
('externlinks', []),
('fileoutput', []),
('gml', {}),
('gxml', {}),
('html', {}),
('ignorewarnings', []),
('internlinks', []),
('localwebroot', None),
('logger', 'TextLogger'),
('loginextrafields', {}),
('loginpasswordfield', 'password'),
('loginurl', None),
('loginuserfield', 'login'),
('maxfilesizedownload', 5242880),
('maxfilesizeparse', 1048576),
('maxhttpredirects', 10),
('maxnumurls', None),
('maxrequestspersecond', 10),
('maxrunseconds', None),
('nntpserver', None),
('none', {}),
('output', 'text'),
('pluginfolders', []),
('proxy', {}),
('quiet', False),
('recursionlevel', 0),
('robotstxt', True),
('sitemap', {}),
('sql', {}),
('sslverify', '/etc/ssl/certs/ca-certificates.crt'),
('status', False),
('status_wait_seconds', 5),
('text', {}),
('threads', 2),
('timeout', 60),
('trace', False),
('useragent',
  u'Mozilla/5.0 (compatible; LinkChecker/9.4.0; +http://wummel.github.io/linkchecker/)'),
('verbose', False),
('warnings', False),
('xml', {})]
DEBUG linkcheck.check 2020-05-13 10:23:27,284 MainThread HttpUrl handles url https://www.wirecard.at/
DEBUG linkcheck.check 2020-05-13 10:23:27,284 MainThread checking syntax
DEBUG linkcheck.check 2020-05-13 10:23:27,284 MainThread Add intern pattern u'^https?://(www\\.|)wirecard\\.at\\/'
DEBUG linkcheck.check 2020-05-13 10:23:27,284 MainThread Link pattern u'^https?://(www\\.|)wirecard\\.at\\/' strict=False
DEBUG linkcheck.cache 2020-05-13 10:23:27,285 MainThread queueing https://www.wirecard.at/
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2020-05-13 10:23:27+002
DEBUG linkcheck.check 2020-05-13 10:23:27,285 CheckThread-https://www.wirecard.at/ Checking https link
base_url=u'https://www.wirecard.at/'
parent_url=None
base_ref=None
recursion_level=0
url_connection=None
line=0
column=0
page=0
name=u''
anchor=u''
cache_url=https://www.wirecard.at/
DEBUG linkcheck.check 2020-05-13 10:23:27,286 CheckThread-https://www.wirecard.at/ checking connection
DEBUG linkcheck.check 2020-05-13 10:23:27,449 CheckThread-https://www.wirecard.at/ u'https://www.wirecard.at/robots.txt' allow all (request error)
DEBUG linkcheck.check 2020-05-13 10:23:27,449 CheckThread-https://www.wirecard.at/ u'https://www.wirecard.at/robots.txt' check allowance for:
  user agent: u'Mozilla/5.0 (compatible; LinkChecker/9.4.0; +http://wummel.github.io/linkchecker/)'
  url: u'https://www.wirecard.at/' ...
DEBUG linkcheck.check 2020-05-13 10:23:27,449 CheckThread-https://www.wirecard.at/  ... allow all.
DEBUG linkcheck.check 2020-05-13 10:23:27,449 CheckThread-https://www.wirecard.at/ Prepare request with {'url': u'https://www.wirecard.at/', 'headers': {}, 'method': 'GET'}
DEBUG linkcheck.check 2020-05-13 10:23:27,450 CheckThread-https://www.wirecard.at/ Send request <PreparedRequest [GET]> with {'stream': True, 'allow_redirects': False, 'verify': '/etc/ssl/certs/ca-certificates.crt', 'timeout': 60}
DEBUG linkcheck.check 2020-05-13 10:23:27,450 CheckThread-https://www.wirecard.at/ Request headers {'Connection': 'keep-alive', 'User-Agent': u'Mozilla/5.0 (compatible; LinkChecker/9.4.0; +http://wummel.github.io/linkchecker/)', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate'}
DEBUG linkcheck.check 2020-05-13 10:23:27,458 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,458 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,459 CheckThread-https://www.wirecard.at/ follow all redirections
DEBUG linkcheck.check 2020-05-13 10:23:27,468 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,468 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,468 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,468 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,478 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,478 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,478 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,478 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,487 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,487 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,487 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,487 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,497 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,497 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,497 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,497 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,506 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,506 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,506 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,506 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,516 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,516 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,516 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,516 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,526 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,526 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,527 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,527 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,535 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,535 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,535 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,535 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,544 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,544 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,545 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,545 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,554 CheckThread-https://www.wirecard.at/ Redirected to u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,554 CheckThread-https://www.wirecard.at/ Intern URL u'https://www.wirecard.at/'
DEBUG linkcheck.check 2020-05-13 10:23:27,555 CheckThread-https://www.wirecard.at/ cannot extract SSL certificate from connection
DEBUG linkcheck.check 2020-05-13 10:23:27,555 CheckThread-https://www.wirecard.at/ Got SSL certificate None
DEBUG linkcheck.check 2020-05-13 10:23:27,555 CheckThread-https://www.wirecard.at/ Error in https://www.wirecard.at/: <class 'requests.exceptions.TooManyRedirects'> Exceeded 10 redirects.
DEBUG linkcheck.check 2020-05-13 10:23:27,555 CheckThread-https://www.wirecard.at/ Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 459, in local_check
    self.check_connection()
  File "/usr/local/lib/python2.7/dist-packages/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 149, in check_connection
    self.follow_redirections(request)
  File "/usr/local/lib/python2.7/dist-packages/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/httpurl.py", line 268, in follow_redirections
    for response in self.get_redirects(request):
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 156, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
TooManyRedirects: Exceeded 10 redirects.


URL        `https://www.wirecard.at/'
Real URL   https://www.wirecard.at/
Check time 0.270 seconds
Size       232B
Info       Redirected to `https://www.wirecard.at/'.
Result     Error: TooManyRedirects: Exceeded 10 redirects.
DEBUG linkcheck.cache 2020-05-13 10:23:27,556 CheckThread-https://www.wirecard.at/ task_done https://www.wirecard.at/

Statistics:
Downloaded: 0B.
Content types: 0 image, 1 text, 0 video, 0 audio, 0 application, 0 mail and 0 other.
URL lengths: min=24, max=24, avg=24.

That's it. 1 link in 1 URL checked. 0 warnings found. 1 error found.
Stopped checking at 2020-05-13 10:23:27+002 (0.32 seconds)
```

**Comment by mgedmin** [comment]
Looks like the web server is doing browser-sniffing or something, because when I test it with httpie, I also get a redirect loop:

```
$ http get https://www.wirecard.at/
HTTP/1.1 301 Moved Permanently
Age: 6719
Connection: keep-alive
Content-Length: 232
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 13 May 2020 08:19:28 GMT
Location: https://www.wirecard.at/
Server: Apache
Via: 1.1 02362f0faae05408640185d927020628.cloudfront.net (CloudFront)
X-Amz-Cf-Id: HqsEQ78cWYeXm_79FVVm2utqYfMjGHB77B8JWYf91fEhXIqoCvSIQg==
X-Amz-Cf-Pop: WAW50-C1
X-Cache: Hit from cloudfront

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.wirecard.at/">here</a>.</p>
</body></html>
```

I also get the 301 redirect with curl, but wget works.

**Comment by reinholdfuereder** [comment]
@mgedmin Thanks for the quick analysis/response/hint!

Do you mean you get a redirect loop (or at least more than "10 redirects" as the error message says)?

And do you mean that this logs are OK or at least not worrying?
```
cannot extract SSL certificate from connection
Got SSL certificate None
```

**Comment by mgedmin** [comment]
> Do you mean you get a redirect loop (or at least more than "10 redirects" as the error message says)?

I get a redirect loop when I try httpie or curl, but not when I try wget or a browser.  The "10 redirects" error message is meant to guard against redirect loops, so linkchecker won't sit there and follow the redirects until the end of time.

> And do you mean that this logs are OK or at least not worrying?

Yes, the "cannot extract SSL certificate from connection" message is not good, but this is a different issue (https://github.com/linkchecker/linkchecker/pull/86), not related to the redirect loop.
