### ISSUE TITLE
Invalid IPv6 URL

### ISSUE THREAD

**Issue by aboettger-tuhh** [linkchecker/linkchecker#204]
```
You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with  .

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html, started 140715769775872)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html, started 140715769775872)>>
      url_data = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7ffaf3327de8>
      url_data = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
      self = <local> <Checker(CheckThread-https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html, started 140715769775872)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7ffaf34a5090>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x7ffaf3327410>
      url_data = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 46, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 55, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x7ffaf3327848>
      url_data = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
      url_data.add_url = <local> <bound method HttpUrl.add_url of <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, co...
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'frame': [u'src', u'longdesc'], 'body': [u'background'], 'layer': [u'background', u'src'], 'html': [u'manifest'], 'script': [u'src'], 'applet': [u'archive', u'src'], 'object': [u'classid', u'data', u'archive', u'usemap', u'codebase'], 'track': [u'src'], 'source': [u'src'], 'tr': [u'background'],..., len = 35
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 135, in find_links
    line: parser.feed(content)
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7ffad97f1100>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7ffad97f1100>
      content = <local> '\n<!DOCTYPE HTML>\n<html lang="de" >\n    <head>\n        <meta charset="UTF-8">\n        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">\n        <title>Aus statisch mach dynamisch \xc2\xb7 Einf\xc3\xbchrung in die Informationstechnik II</title>\n        <meta http-equiv="X-..., len = 67096
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7ffad9788d10>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7ffad9788d10>>
      tag = <local> u'a'
      attr = <local> u'href'
      value = <local> u'http://[IP-Adresse', len = 18
      name = <local> u'http://[IP-Adresse', len = 18
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 277, in parse_tag
    line: self.found_url(value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7ffad9788d10>
      self.found_url = <local> <bound method LinkFinder.found_url of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7ffad9788d10>>
      value = <local> u'http://[IP-Adresse', len = 18
      name = <local> u'http://[IP-Adresse', len = 18
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 283, in found_url
    line: column=self.parser.last_column(), name=name, base=base)
    locals:
      column = <not found>
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7ffad9788d10>
      self.parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7ffad97f1100>
      self.parser.last_column = <local> <built-in method last_column of linkcheck.HtmlParser.htmlsax.parser object at 0x7ffad97f1100>
      name = <local> u'http://[IP-Adresse', len = 18
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 668, in add_url
    line: page=page, name=name, parent_content_type=self.content_type)
    locals:
      page = <local> 0
      name = <local> u'http://[IP-Adresse', len = 18
      parent_content_type = <not found>
      self = <local> <https link, base_url=u'material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/', base_ref=None, recursion_level=1, url_connection=None, line=869, column=17, page=0, name=u'\n       ...
      self.content_type = <local> 'text/html', len = 9
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/__init__.py", line 125, in get_url_from
    line: line=line, column=column, page=page, name=name, extern=extern)
    locals:
      line = <local> 1149
      column = <local> 40
      page = <local> 0
      name = <local> u'http://[IP-Adresse', len = 18
      extern = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 131, in __init__
    line: self.check_syntax()
    locals:
      self = <local> <http link, base_url=u'http://[IP-Adresse', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', base_ref=None, recursion_level=2, url_connection=None, line=1149, column=40, page=0...
      self.check_syntax = <local> <bound method HttpUrl.check_syntax of <http link, base_url=u'http://[IP-Adresse', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', base_ref=None, recursion_level=2, url_connect...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 336, in check_syntax
    line: self.build_url()
    locals:
      self = <local> <http link, base_url=u'http://[IP-Adresse', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', base_ref=None, recursion_level=2, url_connection=None, line=1149, column=40, page=0...
      self.build_url = <local> <bound method HttpUrl.build_url of <http link, base_url=u'http://[IP-Adresse', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', base_ref=None, recursion_level=2, url_connection...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 361, in build_url
    line: base_url, is_idn = url_norm(self.base_url, self.encoding)
    locals:
      base_url = <not found>
      is_idn = <not found>
      url_norm = <global> <function url_norm at 0x7ffaf3ed6e60>
      self = <local> <http link, base_url=u'http://[IP-Adresse', parent_url=u'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html', base_ref=None, recursion_level=2, url_connection=None, line=1149, column=40, page=0...
      self.base_url = <local> u'http://[IP-Adresse', len = 18
      self.encoding = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 75, in url_norm
    line: return urlutil.url_norm(url, encoding=encoding)
    locals:
      urlutil = <global> <module 'linkcheck.url' from '/usr/local/lib/python2.7/site-packages/linkcheck/url.pyc'>
      urlutil.url_norm = <global> <function url_norm at 0x7ffaf4300488>
      url = <local> u'http://[IP-Adresse', len = 18
      encoding = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/url.py", line 314, in url_norm
    line: urlparts = list(urlparse.urlsplit(url))
    locals:
      urlparts = <not found>
      list = <builtin> <type 'list'>
      urlparse = <global> <module 'urlparse' from '/usr/local/lib/python2.7/urlparse.pyc'>
      urlparse.urlsplit = <global> <function urlsplit at 0x7ffaf6f83488>
      url = <local> 'http://[IP-Adresse', len = 18
  File "/usr/local/lib/python2.7/urlparse.py", line 191, in urlsplit
    line: raise ValueError("Invalid IPv6 URL")
    locals:
      ValueError = <builtin> <type 'exceptions.ValueError'>
ValueError: Invalid IPv6 URL
System info:
LinkChecker 9.4.0
Released on: xx.xx.xxxx
Python 2.7.15 (default, Dec 29 2018, 08:23:12) 
[GCC 6.3.0 20170516] on linux2
PYTHONIOENCODING = 'UTF-8'
Modules: Requests, Pysqlite, Sqlite
Local time: 2019-01-28 06:27:17+000
sys.argv: ['/usr/local/bin/linkchecker', '-o', 'xml', '--recursion-level', '10', '--threads', '10', '--no-status', '--no-robots', '--no-warnings', '--check-extern', '--ignore-url=/wp-json', '--ignore-url=/xmlrpc', '--ignore-url', 'https://fonts.gstatic.com/{0,1}$', 'https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/']
LANG = 'C.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2019-01-28 06:27:17,148 CheckThread-https://fizban05.rz.tu-harburg.de/itbh-inf-wise201718/veranstaltungsskript-inf-wise201718/material/sitzungsmaterial/flask/aus-statisch-mach-dynamisch.html internal error occurred
```

**Comment by anarcat** [comment]
i suspect this is the same issue as #148, closing as duplicate.
