### ISSUE TITLE
Providing Error report as requested

### ISSUE THREAD

**Issue by HenryMehta** [linkchecker/linkchecker#262]
I am getting the following error running linkchecker from a python program using `os.system("linkchecker " + website.url + " -oblacklist > " + filename)` where website.url is the name of the url being checked.  There are 11.  I get this message multiple times on some where I run from a Ubuntu server.  I do not get it when I run from my Ubuntu Desktop

```
********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://ultherapy.co.uk/?p=963, started 140464002946816)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://ultherapy.co.uk/?p=963, started 140464002946816)>>
      url_data = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fc06c69ade8>
      url_data = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self = <local> <Checker(CheckThread-https://ultherapy.co.uk/?p=963, started 140464002946816)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fc06bf37610>
  File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=9...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 135, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=...
      request = <local> <PreparedRequest [GET]>
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 165, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p...
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'timeout': 60, 'stream': True, 'allow_redirects': False, 'verify': True}
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 172, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 193, in _add_ssl_info
    line: sock = self._get_ssl_sock()
    locals:
      sock = <not found>
      self = <local> <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p=963>
      self._get_ssl_sock = <local> <bound method HttpUrl._get_ssl_sock of <https link, base_url=u'https://ultherapy.co.uk/?p=963', parent_url=u'https://ultherapy.co.uk/safety-guidelines/', base_ref=None, recursion_level=3, url_connection=None, line=1, column=30271, page=0, name=u'', anchor=u'', cache_url=https://ultherapy.co.uk/?p...
  File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 184, in _get_ssl_sock
    line: if raw_connection.sock is None:
    locals:
      raw_connection = <local> None
      raw_connection.sock = <local> !AttributeError: 'NoneType' object has no attribute 'sock'
      None = <builtin> None
AttributeError: 'NoneType' object has no attribute 'sock'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Requests: 2.22.0
Modules: Sqlite
Local time: 2019-07-05 08:49:55+000
sys.argv: ['/usr/bin/linkchecker', 'https://ultherapy.co.uk', '-oblacklist']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')
```

**Comment by HenryMehta** [comment]
Needed version 9.4
