### ISSUE TITLE
Invalid block type while decompressing

### ISSUE THREAD

**Issue by martindholmes** [linkchecker/linkchecker#27]
First, thanks for taking over this project; it's much appreciated. :-)

We use linkchecker as part of large build processes for web materials running on the Jenkins CI server. Once in a while, this kind of error shows up; I've copied the trace below.

```
********** Oops, I did it again. *************
     [exec] 
     [exec] You have found an internal error in LinkChecker. Please write a bug report
     [exec] at https://github.com/wummel/linkchecker/issues
     [exec] and include the following information:
     [exec] - the URL or file you are testing
     [exec] - the system information below
     [exec] 
     [exec] When using the commandline client:
     [exec] - your commandline arguments and any custom configuration files.
     [exec] - the output of a debug run with option "-Dall"
     [exec] 
     [exec] Not disclosing some of the information above due to privacy reasons is ok.
     [exec] I will try to help you nonetheless, but you have to give me something
     [exec] I can work with ;) .
     [exec] 
     [exec] Traceback (most recent call last):
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/director/task.py", line 29, in run
     [exec]     line: self.run_checked()
     [exec]     locals:
     [exec]       self = <local> <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>
     [exec]       self.run_checked = <local> <bound method Checker.run_checked of <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>>
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 48, in run_checked
     [exec]     line: self.check_url()
     [exec]     locals:
     [exec]       self = <local> <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>
     [exec]       self.check_url = <local> <bound method Checker.check_url of <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>>
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 56, in check_url
     [exec]     line: self.check_url_data(url_data)
     [exec]     locals:
     [exec]       self = <local> <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>
     [exec]       self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/, started 140387817600768)>>
     [exec]       url_data = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/director/checker.py", line 71, in check_url_data
     [exec]     line: url_data.check()
     [exec]     locals:
     [exec]       url_data = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       url_data.check = <local> <bound method HttpUrl.check of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, ...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 489, in check
     [exec]     line: self.local_check()
     [exec]     locals:
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self.local_check = <local> <bound method HttpUrl.local_check of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, colu...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 544, in local_check
     [exec]     line: self.check_content()
     [exec]     locals:
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self.check_content = <local> <bound method HttpUrl.check_content of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, co...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 772, in check_content
     [exec]     line: self.set_title_from_content()
     [exec]     locals:
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self.set_title_from_content = <local> <bound method HttpUrl.set_title_from_content of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, lin...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 263, in set_title_from_content
     [exec]     line: parser.feed(self.get_content())
     [exec]     locals:
     [exec]       parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7fae646a29f0>
     [exec]       parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7fae646a29f0>
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self.get_content = <local> <bound method HttpUrl.get_content of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, colu...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/urlbase.py", line 751, in get_content
     [exec]     line: self.data, self.dlsize = self.read_content()
     [exec]     locals:
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self.data = <local> None
     [exec]       self.dlsize = <local> 20
     [exec]       self.read_content = <local> <bound method HttpUrl.read_content of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, col...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 686, in read_content
     [exec]     line: return self._read_content()
     [exec]     locals:
     [exec]       self = <local> <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, column=4, name=u'social_media', anchor=u'...
     [exec]       self._read_content = <local> <bound method HttpUrl._read_content of <http link, base_url=u'http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/', parent_url=u'file:///var/lib/jenkins/jobs/MoEML/workspace/utilities/tempLinkchecker/linkcheck.htm', base_ref=None, recursion_level=1, url_connection=None, line=974, co...
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/checker/httpurl.py", line 709, in _read_content
     [exec]     line: data = f.read()
     [exec]     locals:
     [exec]       data = <local> '\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xcc\x19\xf9O\xdbH\xf7g\xf8+&^\x95\xd8\x8b=v\x0e\x12\x9a`\x10\rTZ\xa9\xddV\x05\xf4i\xd5Thb\x8f\x8f\xe0kg&\x84\x08\xf2\xbf\xef\x1b\xdb!\xce\xd1\x96,[\xe9\x93P<\xc7\x9bw\xcf;\x86\x93\xda\xc5\xa7\xc1\xf5_\x9f/Q \xe2\xe8t\xffD~PD\x12\xdfVhb\xdc\\)\xc8\x89\x08\..., len = 57040
     [exec]       f = <local> <gzip on 0x7fae6454f560>
     [exec]       f.read = <local> <bound method GzipFile.read of <gzip on 0x7fae6454f560>>
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/gzip2.py", line 247, in read
     [exec]     line: self._read(readsize)
     [exec]     locals:
     [exec]       self = <local> <gzip on 0x7fae6454f560>
     [exec]       self._read = <local> <bound method GzipFile._read of <gzip on 0x7fae6454f560>>
     [exec]       readsize = <local> 16384
     [exec]   File "/usr/lib/python2.7/dist-packages/linkcheck/gzip2.py", line 306, in _read
     [exec]     line: uncompress = self.decompress.decompress(buf)
     [exec]     locals:
     [exec]       uncompress = <not found>
     [exec]       self = <local> <gzip on 0x7fae6454f560>
     [exec]       self.decompress = <local> <zlib.Decompress object at 0x7fae63e52620>
     [exec]       self.decompress.decompress = <local> <built-in method decompress of zlib.Decompress object at 0x7fae63e52620>
     [exec]       buf = <local> '\x1e\xccn\xb0-\x87\x9e\xd7\xba\xda\x93q\x9f!|\xe8\xd692\xaaLr\t(\x03j\n\xb4\x9er\x9d)\x06\xf1Q\xe9"\x8d\x1cp\xea\xcc\xa3\x98\xc1\x8dC\x05\xb9M0\x07\x1d\xf9\xe6\xc8\x0b\xa3\xeaC\t\xe5B\xd2a\xe0m\x19\xa3\x01\x05\x1d\x11\xbb\xea\xfd\xb2\xa3*_\xae\x1cc>\x902\x9b\xeei\x88\xdb#G\x10\x11\xb6a_\xc8\x8aF..., len = 16384
     [exec] error: Error -3 while decompressing: invalid block type
     [exec] System info:
     [exec] LinkChecker 8.6
     [exec] Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
     [exec] [GCC 4.8.4] on linux2
     [exec] Modules: Sqlite
     [exec] Local time: 2017-02-06 11:32:59-007
     [exec] sys.argv: ['/usr/bin/linkchecker', 'utilities/tempLinkchecker/linkcheck.htm', '--quiet', '--no-follow-url=.*', '--file-output=xml/products/linkchecker-out.xml']
     [exec] LANGUAGE = 'en_CA:en'
     [exec] LANG = 'en_CA.UTF-8'
     [exec] Default locale: ('en', 'UTF-8')
     [exec] 
     [exec]  ******** LinkChecker internal error, over and out ********
     [exec] WARNING CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/ internal error occurred
     [exec] WARNING CheckThread-http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/ internal error occurred
```

**Comment by anarcat** [comment]
can you provide us with the URL you believe is causing the problem?

running on  http://www.plannedobsolescence.net/if-you-cant-say-anything-nice/ here gives me a swamp of 500 warnings, but doesn't crash: [dump.txt](https://github.com/linkcheck/linkchecker/files/756100/dump.txt)

**Comment by martindholmes** [comment]
That was the URL that caused the problem. It doesn't usually -- the build runs several times a day, and I've only seen this three or four times in the last few weeks -- but it seems to be on that URL when it hits. My guess would be that that particular server has an intermittent bug which creates ill-formed compressed blocks occasionally, and linkchecker falls over when that happens. If you think this is too trivial to be worth attention, that's absolutely fine. It could fail more gracefully, but it's not a big deal.

**Comment by anarcat** [comment]
thanks for the bug report, in any case... we could probably patch up some error handling around this, for sure - i just wanted to make sure we had a precise report - which we have now. thanks!

**Comment by cjmayo** [comment]
This is a report for LinkChecker 8.6, requests was introduced in 9.0 which automatically decompresses replacing the use of the gzip2.py module that raised the exception. Hopefully that fixed this issue. It would need retesting anyway.
