### ISSUE TITLE
Internal error on HTML files containing non-ascii characters

### ISSUE THREAD

**Issue by tkfu** [linkchecker/linkchecker#317]
## Summary

LinkChecker throws an internal error when given an HTML file containing non-ascii UTF-8 characters.

This error was encountered after installing via `pip install git+https://github.com/linkchecker/linkchecker.git` on MacOS Mojave (10.14.6)

A file for a minimal test case is attached. I've verified that this bug also exists on Ubuntu 18.04 and 16.04.

## Steps to reproduce

 1. Download attached text file and save it as `test.html`, or add any non-ascii character like `ä` or `🤷` or `—` to an otherwise-working HTML file.
 2. Run `linkchecker test.html`

[test.txt](https://github.com/linkchecker/linkchecker/files/3750799/test.txt)

## Actual result

Internal error.

## Expected result

Normal parsing and checking of the file

## Environment

 * Operating system: MacOS Mojave (10.14.6), Ubuntu 16.04, Ubuntu 18.04
 * Linkchecker version: 9.4
 * Python version: 2.7.16
 * Install method: `pip install git+https://github.com/linkchecker/linkchecker.git`
 * Site URL: attached test file

## Configuration file

defaults

## Logs

```
$ linkchecker -Dall --verbose test.html 
DEBUG linkcheck.cmdline 2019-10-21 14:42:34,191 MainThread Python 2.7.16 (default, Sep  2 2019, 11:59:44) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
DEBUG linkcheck.check 2019-10-21 14:42:34,191 MainThread reading configuration from []
INFO linkcheck.cmdline 2019-10-21 14:42:34,204 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
DEBUG linkcheck.cmdline 2019-10-21 14:42:34,206 MainThread configuration: [('aborttimeout', 300),
 ('allowedschemes', []),
 ('authentication', []),
 ('blacklist', {}),
 ('checkextern', False),
 ('cookiefile', None),
 ('csv', {}),
 ('debugmemory', False),
 ('dot', {}),
 ('enabledplugins', []),
 ('externlinks', []),
 ('fileoutput', []),
 ('gml', {}),
 ('gxml', {}),
 ('html', {}),
 ('ignorewarnings', []),
 ('internlinks', []),
 ('localwebroot', None),
 ('logger', 'TextLogger'),
 ('loginextrafields', {}),
 ('loginpasswordfield', 'password'),
 ('loginurl', None),
 ('loginuserfield', 'login'),
 ('maxfilesizedownload', 5242880),
 ('maxfilesizeparse', 1048576),
 ('maxhttpredirects', 10),
 ('maxnumurls', None),
 ('maxrequestspersecond', 10),
 ('maxrunseconds', None),
 ('nntpserver', None),
 ('none', {}),
 ('output', 'text'),
 ('pluginfolders', []),
 ('proxy', {}),
 ('quiet', False),
 ('recursionlevel', -1),
 ('robotstxt', True),
 ('sitemap', {}),
 ('sql', {}),
 ('sslverify', '/usr/local/lib/python2.7/site-packages/certifi/cacert.pem'),
 ('status', True),
 ('status_wait_seconds', 5),
 ('text', {}),
 ('threads', 10),
 ('timeout', 60),
 ('trace', False),
 ('useragent',
  u'Mozilla/5.0 (compatible; LinkChecker/9.4.0; +https://linkchecker.github.io/linkchecker/)'),
 ('verbose', True),
 ('warnings', True),
 ('xml', {})]
DEBUG linkcheck.check 2019-10-21 14:42:34,207 MainThread FileUrl handles url test.html
DEBUG linkcheck.check 2019-10-21 14:42:34,207 MainThread checking syntax
DEBUG linkcheck.check 2019-10-21 14:42:34,208 MainThread Add intern pattern u'file\\:\\/\\/\\/Users\\/oster\\/here\\/gitlab\\/ota\\-connect\\-docs\\/build\\/site\\/'
DEBUG linkcheck.check 2019-10-21 14:42:34,208 MainThread Link pattern u'file\\:\\/\\/\\/Users\\/oster\\/here\\/gitlab\\/ota\\-connect\\-docs\\/build\\/site\\/' strict=False
DEBUG linkcheck.cache 2019-10-21 14:42:34,208 MainThread queueing file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2019-10-21 14:42:34+002
DEBUG linkcheck.check 2019-10-21 14:42:34,210 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html Checking file link
base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html'
parent_url=None
base_ref=None
recursion_level=0
url_connection=None
line=0
column=0
page=0
name=u'test.html'
anchor=u''
cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html
DEBUG linkcheck.check 2019-10-21 14:42:34,210 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html checking connection
DEBUG linkcheck.check 2019-10-21 14:42:34,214 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html checking recursion of u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html' ...
DEBUG linkcheck.check 2019-10-21 14:42:34,215 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html ... yes, recursion.
DEBUG linkcheck.check 2019-10-21 14:42:34,215 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html Get content of u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html'
DEBUG linkcheck.cache 2019-10-21 14:42:34,215 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html task_done file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html, started 123145486659584)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html, started 123145486659584)>>
      url_data = <local> <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/tes...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x101cd8050>
      url_data = <local> <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/tes...
      self = <local> <Checker(CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html, started 123145486659584)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x102e1d450>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x101ccf5f0>
      url_data = <local> <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/tes...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 46, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/tes...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 55, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x101ccfa28>
      url_data = <local> <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitlab/ota-connect-docs/build/site/tes...
      url_data.add_url = <local> <bound method FileUrl.add_url of <file link, base_url=u'file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'test.html', anchor=u'', cache_url=file:///Users/oster/here/gitla...
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'body': [u'background'], 'bgsound': [u'src'], 'head': [u'profile'], 'blockquote': [u'cite'], 'th': [u'background'], 'form': [u'action'], 'track': [u'src'], 'frame': [u'src', u'longdesc'], 'object': [u'classid', u'data', u'archive', u'usemap', u'codebase'], 'layer': [u'background', u'src'], 'ins'..., len = 35
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 135, in find_links
    line: parser.feed(content)
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x102e20d60>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x102e20d60>
      content = <local> u'<!DOCTYPE html>\n<html lang="en">\n<meta charset="utf-8">\n<p>Some text \u2014 but with an em-dash.</p>\n</html>\n', len = 104
TypeError: string arg required
System info:
LinkChecker 9.4.0
Released on: xx.xx.xxxx
Python 2.7.16 (default, Sep  2 2019, 11:59:44) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)] on darwin
Modules: Requests, Pysqlite, Sqlite
Local time: 2019-10-21 14:42:34+002
sys.argv: ['/usr/local/bin/linkchecker', '-Dall', '--verbose', 'test.html']
LC_ALL = 'en_US.UTF-8'
LC_CTYPE = 'UTF-8'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2019-10-21 14:42:34,218 CheckThread-file:///Users/oster/here/gitlab/ota-connect-docs/build/site/test.html internal error occurred

Statistics:
Downloaded: 106B.
No statistics available since no URLs were checked.

That's it. 0 links in 1 URL checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2019-10-21 14:42:34+002 (0.01 seconds)
```

**Comment by mgedmin** [comment]
I can reproduce with current git master, by doing
```
tox -e py27 --notest
.tox/py27/bin/linkchecker /path/to/downloaded/test.html
```

This means we have a hole in our test coverage!

**Comment by tkfu** [comment]
I've submitted #318 to docfix this; it works fine in the 9.4.0 release.

**Comment by mgedmin** [comment]
I **cannot** reproduce if I drop test.html into the testsuite with the following patch!

```diff
diff --git a/tests/checker/data/utf8.html b/tests/checker/data/utf8.html
new file mode 100644
index 00000000..c369b145
--- /dev/null
+++ b/tests/checker/data/utf8.html
@@ -0,0 +1,5 @@
+<!DOCTYPE html>
+<html lang="en">
+<meta charset="utf-8">
+<p>Some text — but with an em-dash.</p>
+</html>
diff --git a/tests/checker/data/utf8.html.result b/tests/checker/data/utf8.html.result
new file mode 100644
index 00000000..e69de29b
diff --git a/tests/checker/test_misc.py b/tests/checker/test_misc.py
index f9591f9d..24d18034 100644
--- a/tests/checker/test_misc.py
+++ b/tests/checker/test_misc.py
@@ -33,6 +33,9 @@ class TestMisc (LinkCheckTest):
     def test_html5 (self):
         self.file_test("html5.html")
 
+    def test_utf8 (self):
+        self.file_test("utf8.html")
+
     @need_network
     def test_archive (self):
         self.file_test("archive.html")
```

**Comment by mgedmin** [comment]
git bisect says that commit 5fc01455b7e2707509accaa58a586f7d1dc41443 introduced this bug.

@cjmayo, could you take a look?

**Comment by mgedmin** [comment]
AFAIU the problem happens because the aforementioned commit changed `url_data.get_content()` to return unicode rather than bytes, but the old C-based HTMLParser wants bytes?

Applying the following patch makes the problem go away:

```diff
diff --git a/linkcheck/parser/__init__.py b/linkcheck/parser/__init__.py
index 7f6ad51b..45f8e84d 100644
--- a/linkcheck/parser/__init__.py
+++ b/linkcheck/parser/__init__.py
@@ -130,7 +130,7 @@ def find_links (url_data, callback, tags):
     handler.parser = parser
     # parse
     try:
-        content = url_data.get_content()
+        content = url_data.get_raw_content()
         with parse_mutex:
             parser.feed(content)
             parser.flush()
```

but I would like to have a failing regression test before I propose that as a PR.

**Comment by mgedmin** [comment]
There are quite a few locations where the return value of `get_content()` is fed to some parser.  We should review them all.  E.g. I don't think PdfParser() should be working with unicode strings.

```
$ git grep -w 'get_content *()'
linkcheck/checker/httpurl.py:            parser.feed(self.get_content())
linkcheck/checker/urlbase.py:        """Indicate wether url get_content() can be called."""
linkcheck/parser/__init__.py:    for url, name, lineno in parse_bookmark_data(url_data.get_content()):
linkcheck/parser/__init__.py:    for url, name in parse_bookmark_data(url_data.get_content()):
linkcheck/parser/__init__.py:    for line in url_data.get_content().splitlines():
linkcheck/parser/__init__.py:    for line in strip_comments(url_data.get_content()).splitlines():
linkcheck/parser/__init__.py:    for mo in linkfinder(url_data.get_content()):
linkcheck/parser/sitemap.py:        data = url_data.get_content()
linkcheck/plugins/markdowncheck.py:        content = url_data.get_content()
linkcheck/plugins/parsepdf.py:        data = url_data.get_content()
linkcheck/plugins/parseword.py:        content = url_data.get_content()
linkcheck/plugins/regexcheck.py:        content = url_data.get_content()
linkcheck/plugins/viruscheck.py:        data = url_data.get_content()
```
```

**Comment by tkfu** [comment]
Y'all are amazing, thanks for the amazingly quick response!

**Comment by mgedmin** [comment]
Another thing I noticed: when linkchecker fails with an internal error, the exit status is 0.

According to the [script source](https://github.com/linkchecker/linkchecker/blob/895dc016b97110e318b1cefa2fea45b976fc83f3/linkchecker#L617-L618), it should be 2.

**Comment by mgedmin** [comment]
Meanwhile I've got a failing regression test!

The `test_file()` helper was only looking at the diff in emitted warnings and was silently ignoring any internal errors.  I propose we fix that.
