### ISSUE TITLE
Error when encountering swf files

### ISSUE THREAD

**Issue by mimi89999** [linkchecker/linkchecker#372]
## Summary

Linkchecker error on `.swf` files

## Steps to reproduce

 1.  `linkchecker --threads 40 https://staszic.waw.pl/ --no-follow-url https://staszic.waw.pl/archive/200[0-9]/`
 2. Wait
 3. You can also try `linkchecker https://staszic.waw.pl/files/560x100_2.swf`

## Actual result

```
WARNING bs4.dammit 2020-04-25 10:55:34,205 CheckThread-b'https://staszic.waw.pl/files/560x100_2.swf' Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/home/michel/git/linkchecker/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-b'https://staszic.waw.pl/files/560x100_2.swf', started 140674070476544)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-b'https://staszic.waw.pl/files/560x100_2.swf', started 140674070476544)>>
      url_data = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
  File "/home/michel/git/linkchecker/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7ff1c9cc4dc0>
      url_data = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
      self = <local> <Checker(CheckThread-b'https://staszic.waw.pl/files/560x100_2.swf', started 140674070476544)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7ff1c9c01670>
  File "/home/michel/git/linkchecker/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/home/michel/git/linkchecker/linkcheck/parser/__init__.py'>
      parser.parse_url = <global> <function parse_url at 0x7ff1c9cc45e0>
      url_data = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
  File "/home/michel/git/linkchecker/linkcheck/parser/__init__.py", line 41, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_swf'
      url_data = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
  File "/home/michel/git/linkchecker/linkcheck/parser/__init__.py", line 104, in parse_swf
    line: for mo in linkfinder(url_data.get_content()):
    locals:
      mo = <not found>
      linkfinder = <local> <built-in method finditer of re.Pattern object at 0x2a76d90>
      url_data = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
      url_data.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>>
  File "/home/michel/git/linkchecker/linkcheck/checker/httpurl.py", line 306, in get_content
    line: self.text = self.data.decode(self.soup.original_encoding)
    locals:
      self = <local> <https link, base_url='../files/560x100_2.swf', parent_url='https://staszic.waw.pl/article/1135', base_ref=None, recursion_level=4, url_connection=None, line=801, column=35, page=0, name='', anchor='', cache_url=https://staszic.waw.pl/files/560x100_2.swf>
      self.text = <local> None
      self.data = <local> b'CWS\n\x16\x03\x01\x00x\x9c\xd4\xbbwXS\xcd\xd67<\t\x84\x12\x8a\x94\x84&B\xa4\'\xf4*\xbd\xf7N\nUP\x9a\xf4\x8eHSB\x15i"MAD:\x84& E\x01\x05i\x02V0 \xc5\x82"\x88\x08\n"\xa0"\xf0\x05\xcf\xb9\xef\xf3\x9c\xf7<\xef\xf3\xbe\xd7\xf7\xfd\xf5\xe5"\x9b5k\xd6\xfa\xcd\xec\xb5\xd7\xac5;3\x13\t`\x91\x00P-\x03\xc...
      self.data.decode = <local> <built-in method decode of bytes object at 0x2d4f350>
      self.soup = <local> CWS
x�ԻwXS��7&lt;	����&amp;B�'�*��N
UP��HSBi"MAD:�&amp; EiV0 ł"�
&amp;����)� ��,-+%#}�CR����׬5;3	`�P-���,�8v6�gT�������0UJIC�;&lt;<xuz�ܹsr�䥂b��eutt�e���$)�aq�ᮑ��a�����a�>��&gt;A��ò�[��p
                        �t
��k�J�
      �]üQ֡Ag&lt;��(��(=���"J�v���...
      self.soup.original_encoding = <local> 'utf-8'
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 9: invalid start byte
System info:
LinkChecker 9.4.0
Released on: xx.xx.xxxx
Python 3.8.2 (default, Apr  1 2020, 15:52:55) 
[GCC 9.3.0] on linux
Modules: Requests, Pysqlite, Sqlite
Local time: 2020-04-25 10:55:34+002
sys.argv: ['./linkchecker', '--threads', '40', 'https://staszic.waw.pl/', '--no-follow-url', 'https://staszic.waw.pl/archive/200[0-9]/']
LANG = 'fr_FR.utf8'
Default locale: ('fr', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2020-04-25 10:55:34,223 CheckThread-b'https://staszic.waw.pl/files/560x100_2.swf' internal error occurred
```

## Expected result

No error

## Environment

 * Operating system: `Linux debian 5.5.0-1-amd64 #1 SMP Debian 5.5.13-2 (2020-03-30) x86_64 GNU/Linux`
 * Linkchecker version: 8707931
 * Python version: `3.8.2`
 * Install method: git
 * Site URL: https://staszic.waw.pl/

## Configuration file

None

**Comment by mgedmin** [comment]
https://staszic.waw.pl/files/560x100_2.swf is correctly served with

```
Content-Type: application/x-shockwave-flash
```

so I wonder why `self.soup.original_encoding` get set to `'utf-8'`?

We have a SWF file in our test suite, and `TestHttpMisc.swf_test` does call into `parse_swf`, at which point `url_data.encoding` is `None`, and when we call `make_soap(self.data, self.encoding)` we end up with a `soap.original_encoding` being `'iso-8859-1'`.

So it's BeautifulSoap doing encoding guessing on binary data, and it gets something working for our test file, but gets it wrong in real life.

The right thing is to avoid decoding SWF data into unicode, which is what #373 is about.
