### ISSUE TITLE
Please help me compile for Windows

### ISSUE THREAD

**Issue by s0ftimage** [linkchecker/linkchecker#381]
Hello,

I am trying to compile 9.4 for Windows, because our old 9.3 version was failing making HTTPS (TLS) calls. I am hoping that LinkChecker 9.4 + Python 3.8 will resolve the TLS issue. Can someone please help me?

This is what I see when I try to build:

c:\Temp\trial\LinkChecker-9.4.0>windows\build.bat
creating c:\Temp\trial\LinkChecker-9.4.0_LinkChecker_configdata.py
running sdist
running check
reading manifest template 'MANIFEST.in'
warning: no files found matching 'doc\html*.ico'
warning: no files found matching 'doc\html*.html'
warning: no files found matching 'doc\html*.txt'
warning: no files found matching 'doc\html*.png'
warning: no files found matching 'doc\html*.qhp'
warning: no files found matching 'doc\html*.qhcp'
warning: no files found matching 'doc\html\Makefile'
writing manifest file 'MANIFEST'
Traceback (most recent call last):
File "setup.py", line 356, in
setup(
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools_init_.py", line 144, in setup
return distutils.core.setup(**attrs)
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
dist.run_commands()
File "setup.py", line 224, in run_commands
super(MyDistribution, self).run_commands()
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
self.run_command(cmd)
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
cmd_obj.run()
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 152, in run
self.get_file_list()
File "setup.py", line 316, in get_file_list
super(MySdist, self).get_file_list()
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 208, in get_file_list
self.write_manifest()
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 389, in write_manifest
self.execute(file_util.write_file, (self.manifest, content),
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 335, in execute
util.execute(func, args, msg, dry_run=self.dry_run)
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\util.py", line 303, in execute
func(*args)
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\file_util.py", line 236, in write_file
f.write(line + "\n")
File "C:\Users<user>\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-25: character maps to
creating c:\Temp\trial\LinkChecker-9.4.0_LinkChecker_configdata.py
running build
running build_py
running build_scripts

Then NOTHING happens, I cannot find LinkChecker.exe

**Comment by s0ftimage** [comment]
Hello,

I am trying to compile 9.4 for Windows, because our old 9.3 version was failing making HTTPS (TLS) calls.  I am hoping that LinkChecker 9.4 + Python 3.8 will resolve the TLS issue.  Can someone please help me?

This is what I see when I try to build:

c:\Temp\trial\LinkChecker-9.4.0>windows\build.bat
creating c:\Temp\trial\LinkChecker-9.4.0\_LinkChecker_configdata.py
running sdist
running check
reading manifest template 'MANIFEST.in'
warning: no files found matching 'doc\html\*.ico'
warning: no files found matching 'doc\html\*.html'
warning: no files found matching 'doc\html\*.txt'
warning: no files found matching 'doc\html\*.png'
warning: no files found matching 'doc\html\*.qhp'
warning: no files found matching 'doc\html\*.qhcp'
warning: no files found matching 'doc\html\Makefile'
writing manifest file 'MANIFEST'
Traceback (most recent call last):
  File "setup.py", line 356, in <module>
    setup(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "setup.py", line 224, in run_commands
    super(MyDistribution, self).run_commands()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 152, in run
    self.get_file_list()
  File "setup.py", line 316, in get_file_list
    super(MySdist, self).get_file_list()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 208, in get_file_list
    self.write_manifest()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\command\sdist.py", line 389, in write_manifest
    self.execute(file_util.write_file, (self.manifest, content),
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\cmd.py", line 335, in execute
    util.execute(func, args, msg, dry_run=self.dry_run)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\util.py", line 303, in execute
    func(*args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\distutils\file_util.py", line 236, in write_file
    f.write(line + "\n")
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-25: character maps to <undefined>
creating c:\Temp\trial\LinkChecker-9.4.0\_LinkChecker_configdata.py
running build
running build_py
running build_scripts

Then NOTHING happens, I cannot find LinkChecker.exe

**Comment by thezoggy** [comment]
windows build system is setup for python 2.x not 3.x.. so its clearly out of date and not meant to be used with the current python3.x code (until someone updates it)

**Comment by cjmayo** [comment]
The combination of LinkChecker 9.4 + Python 3.8 won't work, 9.4 is Python 2 only.

Do use `pip` and LinkChecker from git: e.g. `pip3 install git+https://github.com/linkchecker/linkchecker.git` (or download a zip: https://github.com/linkchecker/linkchecker/archive/master.zip
and use `pip3 install master.zip`).

There are a few notes for Windows in:
https://github.com/linkchecker/linkchecker/blob/master/doc/install.txt
