### ISSUE TITLE
TypeError: decode() argument 'encoding' must be str, not None

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#392]
## Summary

I decided to test if git master is working, so I dug out my checklinks.sh that I used for my static website and ran it.

lnkchecker promptly crashed.

## Steps to reproduce

 1. git clone https://github.com/mgedmin/gedmin.as
 2. cd gedmin.as
 3. make
 4. pip install --user ~/src/linkchecker/
 5. ./checklinks.sh

## Actual result

```
INFO linkcheck.cmdline 2020-05-17 21:24:05,816 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.0.0.dev0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2020-05-17 21:24:05+003


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/home/mg/src/linkchecker/linkcheck/director/checker.py", line 103, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-b'file:///home/mg/src/gedmin.as/website/_site/googleb2dda1ae8861a21d.html', started 139644486285056)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-b'file:///home/mg/src/gedmin.as/website/_site/googleb2dda1ae8861a21d.html', started 139644486285056)>>
      url_data = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
  File "/home/mg/src/linkchecker/linkcheck/director/checker.py", line 119, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f019d909e50>
      url_data = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
      self = <local> <Checker(CheckThread-b'file:///home/mg/src/gedmin.as/website/_site/googleb2dda1ae8861a21d.html', started 139644486285056)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f019b404d90>
  File "/home/mg/src/linkchecker/linkcheck/director/checker.py", line 63, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/home/mg/src/linkchecker/linkcheck/parser/__init__.py'>
      parser.parse_url = <global> <function parse_url at 0x7f019d9090d0>
      url_data = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
  File "/home/mg/src/linkchecker/linkcheck/parser/__init__.py", line 39, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html'
      url_data = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
  File "/home/mg/src/linkchecker/linkcheck/parser/__init__.py", line 48, in parse_html
    line: linkparse.find_links(url_data.get_soup(), url_data.add_url, linkparse.LinkTags)
    locals:
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/home/mg/src/linkchecker/linkcheck/htmlutil/linkparse.py'>
      linkparse.find_links = <global> <function find_links at 0x7f019d909550>
      url_data = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
      url_data.get_soup = <local> <bound method UrlBase.get_soup of <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/m...
      url_data.add_url = <local> <bound method FileUrl.add_url of <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg...
      linkparse.LinkTags = <global> {'a': ['href'], 'applet': ['archive', 'src'], 'area': ['href'], 'audio': ['src'], 'bgsound': ['src'], 'blockquote': ['cite'], 'body': ['background'], 'button': ['formaction'], 'del': ['cite'], 'embed': ['pluginspage', 'src'], 'form': ['action'], 'frame': ['src', 'longdesc'], 'head': ['profile'], ...
  File "/home/mg/src/linkchecker/linkcheck/checker/urlbase.py", line 627, in get_soup
    line: self.get_content()
    locals:
      self = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
      self.get_content = <local> <bound method UrlBase.get_content of <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///hom...
  File "/home/mg/src/linkchecker/linkcheck/checker/urlbase.py", line 639, in get_content
    line: self.text = self.data.decode(self.soup.original_encoding)
    locals:
      self = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
      self.text = <local> None
      self.data = <local> b''
      self.data.decode = <local> <built-in method decode of bytes object at 0x7f019fca85a0>
      self.soup = <local> 
      self.soup.original_encoding = <local> None
TypeError: decode() argument 'encoding' must be str, not None
System info:
LinkChecker 10.0.0.dev0
Released on: xx.xx.xxxx
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
PYTHONSTARTUP = '/home/mg/.python'
Modules: Requests, Argcomplete, Pysqlite, Sqlite
Local time: 2020-05-17 21:24:05+003
sys.argv: ['/home/mg/src/linkchecker/.tox/py38/bin/linkchecker', '-f', 'linkcheckerrc', 'website/_site/']
LC_CTYPE = 'lt_LT.UTF-8'
LANG = 'lt_LT.UTF-8'
Default locale: ('lt', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2020-05-17 21:24:05,862 CheckThread-b'file:///home/mg/src/gedmin.as/website/_site/googleb2dda1ae8861a21d.html' internal error occurred
10 threads active,   145 links queued,  413 links in 568 URLs checked, runtime 1 seconds

Statistics:
Downloaded: 2.34MB.
Content types: 86 image, 273 text, 0 video, 0 audio, 307 application, 2 mail and 395 other.
URL lengths: min=15, max=115, avg=59.

That's it. 1063 links in 1064 URLs checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2020-05-17 21:24:11+003 (5 seconds)
```

(if you pay close attention you'll notice that I didn't do what the steps-to-reproduce said; instead of pip installing linkchecker into my home directory I reused a tox virtualenv in my linkchecker tree.)

## Expected result

No crash.

## Environment

 * Operating system: Ubuntu 20.04 LTS
 * Linkchecker version: tip of the https://github.com/linkchecker/linkchecker/tree/dev-version branch actually
 * Python version: 3.8
 * Install method: pip install into a virtualenv
 * Site URL: files on disk

## Configuration file

https://github.com/mgedmin/gedmin.as/blob/200776c32f020f37e31752510bbbcb66f8fa3ee7/linkcheckerrc

## Logs

oh come on this is overkill

**Comment by mgedmin** [comment]
The salient point is

```
  File "/home/mg/src/linkchecker/linkcheck/checker/urlbase.py", line 639, in get_content
    line: self.text = self.data.decode(self.soup.original_encoding)
    locals:
      self = <local> <file link, base_url='googleb2dda1ae8861a21d.html', parent_url='file:///home/mg/src/gedmin.as/website/_site/', base_ref=None, recursion_level=1, url_connection=None, line=3, column=1, page=0, name='googleb2dda1ae8861a21d.html', anchor='', cache_url=file:///home/mg/src/gedmin.as/website/_site/goog...
      self.text = <local> None
      self.data = <local> b''
      self.soup.original_encoding = <local> None
```

This is an empty file, and BeautifulSoup decides that original encoding is meaningless for it, so it uses None instead of something sensible and universal like UTF-8.

I have to say multithreading makes pdb painful to use.  --threads=0 or -1 does not disable them, despite what --help promises!  Turning on debug options with -D does not disable threads, despite what --help promises!

I'm going to stop now and maybe come back later when I feel more ready for infrastructural improvements.

**Comment by anarcat** [comment]
@cjmayo this seems related to the BS4 rewrite, could you take a look? it seems simple enough that we might just need to do a `if encoding is None: be_smarter()` or something :p

**Comment by mgedmin** [comment]
> I have to say multithreading makes pdb painful to use. --threads=0 or -1 does not disable them, despite what --help promises! Turning on debug options with -D does not disable threads, despite what --help promises!

Turns out it does disable HTTP checking threads, but linkchecker also has a status thread that prints those "N threads active, ..." messages every 5 seconds.  And you can turn that off with --no-status.

**Comment by mgedmin** [comment]
Reopening because this affects HTTP requests too.
