### ISSUE TITLE
Linkchecker fails with URL with a square bracket

### ISSUE THREAD

**Issue by wkoszek** [linkchecker/linkchecker#43]
Linkchecker is failing when run on the file attached. I don't know for sure, but quickly skimming at the log and seeing .md files, looks like I've made a mistake in one of my `.md` files:

```
2017-02-13-learn-programming-self-study-guide.html.md:*(Photo by [Joseph Yates](https://unsplash.com/@josephyates\_) via [Unsplash](https://www.unsplash.com]))*
```

[i.html.gz](https://github.com/linkcheck/linkchecker/files/805886/i.html.gz)

```
[22:17:04][wk@wkoszek_mba:~/r/me]$ linkchecker build//blog/2017/02/13/learn-programming-self-study-guide/index.html
INFO 2017-02-27 22:17:15,381 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2017-02-27 22:17:15-007


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html, started 123145312403456)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html, started 123145312403456)>>
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x1103f6668>
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
      self = <local> <Checker(CheckThread-file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html, started 123145312403456)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x110f43f50>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x1103efc80>
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 39, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 48, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x1103f6140>
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
      url_data.add_url = <local> <bound method FileUrl.add_url of <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-se...
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'body': [u'background'], 'bgsound': [u'src'], 'head': [u'profile'], 'blockquote': [u'cite'], 'th': [u'background'], 'form': [u'action'], 'track': [u'src'], 'frame': [u'src', u'longdesc'], 'object': [u'classid', u'data', u'archive', u'usemap', u'codebase'], 'layer': [u'background', u'src'], 'ins'..., len = 35
  File "/usr/local/lib/python2.7/site-packages/linkcheck/parser/__init__.py", line 126, in find_links
    line: parser.feed(url_data.get_content())
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x11045dcb0>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x11045dcb0>
      url_data = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
      url_data.get_content = <local> <bound method FileUrl.get_content of <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programmin...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x110151550>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x110151550>>
      tag = <local> u'a'
      attr = <local> u'href'
      value = <local> u'https://www.unsplash.com]', len = 25
      name = <local> u'Unsplash', len = 8
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 277, in parse_tag
    line: self.found_url(value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x110151550>
      self.found_url = <local> <bound method LinkFinder.found_url of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x110151550>>
      value = <local> u'https://www.unsplash.com]', len = 25
      name = <local> u'Unsplash', len = 8
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/htmlutil/linkparse.py", line 283, in found_url
    line: column=self.parser.last_column(), name=name, base=base)
    locals:
      column = <not found>
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x110151550>
      self.parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x11045dcb0>
      self.parser.last_column = <local> <built-in method last_column of linkcheck.HtmlParser.htmlsax.parser object at 0x11045dcb0>
      name = <local> u'Unsplash', len = 8
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/fileurl.py", line 282, in add_url
    line: super(FileUrl, self).add_url(url, line=line, column=column, page=page, name=name, base=base)
    locals:
      super = <builtin> <type 'super'>
      FileUrl = <global> <class 'linkcheck.checker.fileurl.FileUrl'>
      self = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
      add_url = <not found>
      url = <local> u'https://www.unsplash.com]', len = 25
      line = <local> 14
      column = <local> 4758
      page = <local> 0
      name = <local> u'Unsplash', len = 8
      base = <local> u''
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 653, in add_url
    line: page=page, name=name, parent_content_type=self.content_type)
    locals:
      page = <local> 0
      name = <local> u'Unsplash', len = 8
      parent_content_type = <not found>
      self = <local> <file link, base_url=u'file:///Users/wk/r/me/build//blog/2017/02/13/learn-programming-self-study-guide/index.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'build//blog/2017/02/13/learn-programming-self-study-guide/index.html', ancho...
      self.content_type = <local> 'text/html', len = 9
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/__init__.py", line 125, in get_url_from
    line: line=line, column=column, page=page, name=name, extern=extern)
    locals:
      line = <local> 14
      column = <local> 4758
      page = <local> 0
      name = <local> u'Unsplash', len = 8
      extern = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 118, in __init__
    line: self.check_syntax()
    locals:
      self = <local> <https link, base_url=u'https://www.unsplash.com]', parent_url=u'file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=4758, page=0, name=u'Unsplash', anchor=None, cache_url=None>
      self.check_syntax = <local> <bound method HttpUrl.check_syntax of <https link, base_url=u'https://www.unsplash.com]', parent_url=u'file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=4758, page=0, name=u'Unsplash',...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 323, in check_syntax
    line: self.build_url()
    locals:
      self = <local> <https link, base_url=u'https://www.unsplash.com]', parent_url=u'file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=4758, page=0, name=u'Unsplash', anchor=None, cache_url=None>
      self.build_url = <local> <bound method HttpUrl.build_url of <https link, base_url=u'https://www.unsplash.com]', parent_url=u'file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=4758, page=0, name=u'Unsplash', an...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 348, in build_url
    line: base_url, is_idn = url_norm(self.base_url, self.encoding)
    locals:
      base_url = <not found>
      is_idn = <not found>
      url_norm = <global> <function url_norm at 0x11028bf50>
      self = <local> <https link, base_url=u'https://www.unsplash.com]', parent_url=u'file:///Users/wk/r/me/build/blog/2017/02/13/learn-programming-self-study-guide/index.html', base_ref=None, recursion_level=1, url_connection=None, line=14, column=4758, page=0, name=u'Unsplash', anchor=None, cache_url=None>
      self.base_url = <local> u'https://www.unsplash.com]', len = 25
      self.encoding = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 62, in url_norm
    line: return urlutil.url_norm(url, encoding=encoding)
    locals:
      urlutil = <global> <module 'linkcheck.url' from '/usr/local/lib/python2.7/site-packages/linkcheck/url.pyc'>
      urlutil.url_norm = <global> <function url_norm at 0x11047ae60>
      url = <local> u'https://www.unsplash.com]', len = 25
      encoding = <local> None
  File "/usr/local/lib/python2.7/site-packages/linkcheck/url.py", line 301, in url_norm

Statistics:
Downloaded: 21.34KB.
    line: urlparts = list(urlparse.urlsplit(url))
    locals:
      urlparts = <not found>
      list = <builtin> <type 'list'>
      urlparse = <global> <module 'urlparse' from '/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.pyc'>
Content types: 0 image, 1 text, 0 video, 0 audio, 0 application, 0 mail and 20 other.
URL lengths: min=8, max=90, avg=31.

      urlparse.urlsplit = <global> <function urlsplit at 0x10fb0eed8>That's it. 21 links in 1 URL checked. 0 warnings found. 0 errors found.

      url = <local> 'https://www.unsplash.com]', len = 25
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 214, in urlsplit
Stopped checking at 2017-02-27 22:17:15-007 (0.08 seconds)
    line: raise ValueError("Invalid IPv6 URL")
    locals:
      ValueError = <builtin> <type 'exceptions.ValueError'>
ValueError: Invalid IPv6 URL
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Requests: 2.5.3
Qt: 4.8.7 / PyQt: 4.11.4
Modules: Sqlite
Local time: 2017-02-27 22:17:15-007
sys.argv: ['/usr/local/bin/linkchecker', 'build//blog/2017/02/13/learn-programming-self-study-guide/index.html']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')
```

**Comment by anarcat** [comment]
while linkchecker shouldn't crash, ever, we can hardly expect to parse *any* document format out there (in this case, markdown) out of the box (although that could be an interesting extension in the future).

so yeah, we should probably catch that ValueError somewhere, but don't expect linkchecker to validate your markdown files for now...

**Comment by mgedmin** [comment]
AFAIU @wkoszek wasn't running linkchecker on the markdown file directly, but rather on the HTML file generated from that markdown.

Linkchecker should be catching ValueError raised by `urllib.urlparse()` when it gets invalid URLs and reporting then ignoring those links, IMHO.

**Comment by anarcat** [comment]
oh i see... of course...

**Comment by wkoszek** [comment]
@mgedmin @anarcat Yes. I provided a failing test case in the attached `.gz` file.

**Comment by cjmayo** [comment]
I've posted a fix: https://github.com/linkchecker/linkchecker/pull/473
