### ISSUE TITLE
linkchecker crashes on older beautifulsoup versions

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#530]
## Summary

linkchecker 10 crashes when running in Debian stable, which has an older version of beautiful soup

## Steps to reproduce

 1. install linkchecker 10 on Debian stable
 2. look at it crash

## Actual result

It crashes.

## Expected result

It should either not crash, or at least not be installable without forcing a backport of bs4. Specifically, the `requirements.txt` doesn't set a lower bound on versions...

## Environment

 * Operating system: Debian GNU/Linux 10 (buster)
 * Linkchecker version: LinkChecker 10.0.0 released 15.1.2021
 * Python version: Python 2.7.16, although i suspect Python 3.7.3 is actually used
 * Install method: installed from a Debian package built from the Debian branch here
 * Site URL: twhatever

## Configuration file

irrelevant.

## Logs

```
anarcat@curie:build-area(main)$ linkchecker --check-extern --no-robots --recursion-level 1 https://anarc.at/blog/2021-01-13-new-phone/
WARNING linkcheck.check 2021-01-27 16:15:34,283 MainThread The blacklist section in linkcheckerrc is deprecated, please rename to failures
LinkChecker 10.0.0
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2020 LinkChecker Authors
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it under
certain conditions. Look at the file `LICENSE' within this distribution.
Récupérez la dernière version sur https://linkchecker.github.io/linkchecker/
Écrivez des commentaires et rapports de bogue à https://github.com/linkchecker/linkchecker/issues

Démarrage du contrôle à 2021-01-27 16:15:34-004


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/linkcheck/director/checker.py", line 103, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://anarc.at/blog/2021-01-13-new-phone/, started 140459674920704)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://anarc.at/blog/2021-01-13-new-phone/, started 140459674920704)>>
      url_data = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
  File "/usr/lib/python3/dist-packages/linkcheck/director/checker.py", line 115, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fbf54385730>
      url_data = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self = <local> <Checker(CheckThread-https://anarc.at/blog/2021-01-13-new-phone/, started 140459674920704)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fbf528e2828>
  File "/usr/lib/python3/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: do_parse = url_data.check_content()
    locals:
      do_parse = <not found>
      url_data = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      url_data.check_content = <local> <bound method UrlBase.check_content of <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>>
  File "/usr/lib/python3/dist-packages/linkcheck/checker/urlbase.py", line 549, in check_content
    line: if self.allows_recursion():
    locals:
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.allows_recursion = <local> <bound method UrlBase.allows_recursion of <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>>
  File "/usr/lib/python3/dist-packages/linkcheck/checker/urlbase.py", line 647, in allows_recursion
    line: if not self.content_allows_robots():
    locals:
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.content_allows_robots = <local> <bound method HttpUrl.content_allows_robots of <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>>
  File "/usr/lib/python3/dist-packages/linkcheck/checker/httpurl.py", line 98, in content_allows_robots
    line: soup = self.get_soup()
    locals:
      soup = <not found>
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.get_soup = <local> <bound method UrlBase.get_soup of <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>>
  File "/usr/lib/python3/dist-packages/linkcheck/checker/urlbase.py", line 710, in get_soup
    line: self.get_content()
    locals:
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>>
  File "/usr/lib/python3/dist-packages/linkcheck/checker/httpurl.py", line 318, in get_content
    line: return super().get_content(self.encoding)
    locals:
      super = <builtin> <class 'super'>
      get_content = <not found>
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.encoding = <local> 'UTF-8'
  File "/usr/lib/python3/dist-packages/linkcheck/checker/urlbase.py", line 721, in get_content
    line: self.soup = htmlsoup.make_soup(self.data, encoding)
    locals:
      self = <local> <https link, base_url='https://anarc.at/blog/2021-01-13-new-phone/', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://anarc.at/blog/2021-01-13-new-phone/>
      self.soup = <local> None
      htmlsoup = <global> <module 'linkcheck.htmlutil.htmlsoup' from '/usr/lib/python3/dist-packages/linkcheck/htmlutil/htmlsoup.py'>
      htmlsoup.make_soup = <global> <function make_soup at 0x7fbf57930400>
      self.data = <local> b'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <!-- The above 3 meta tags *..., len = 29897
      encoding = <local> 'UTF-8'
  File "/usr/lib/python3/dist-packages/linkcheck/htmlutil/htmlsoup.py", line 34, in make_soup
    line: markup, "html.parser", from_encoding=from_encoding, multi_valued_attributes=None
    locals:
      markup = <local> b'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <!-- The above 3 meta tags *..., len = 29897
      from_encoding = <local> 'UTF-8'
      multi_valued_attributes = <not found>
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 183, in __init__
    line: "__init__() got an unexpected keyword argument '%s'" % arg)
    locals:
      arg = <local> 'multi_valued_attributes', len = 23
TypeError: __init__() got an unexpected keyword argument 'multi_valued_attributes'
Info système :
LinkChecker 10.0.0
Released on: 15.1.2021
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
PYTHONSTARTUP = '/home/anarcat/.pythonrc.py'
Modules: Beautiful Soup, dnspython, Requests, PyXDG, Argcomplete, GeoIP, Pysqlite, Sqlite, PyGObject
Local time: 2021-01-27 16:15:34-004
sys.argv: ['/usr/bin/linkchecker', '--check-extern', '--no-robots', '--recursion-level', '1', 'https://anarc.at/blog/2021-01-13-new-phone/']
LANG = 'fr_CA.UTF-8'
Default locale: ('fr', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2021-01-27 16:15:34,536 CheckThread-https://anarc.at/blog/2021-01-13-new-phone/ internal error occurred

Statistiques :
Downloaded: 29.20KB.
No statistics available since no URLs were checked.

Fin. 0 links in 1 URL checked. 0 avertissements trouvées.. 0 erreurs trouvées..
There was 1 internal error.
Stopped checking at 2021-01-27 16:15:35-004 (1 secondes)
```

## Other notes

Sorry for the bugs folks, but this would seem like an important improvement. It shouldn't matter for Debian unstable, which will have an up to date bs4 release, but it will matter for backports or naive users like me that will try the unstable release in stable...

**Comment by cjmayo** [comment]
So, we went to some effort to support bs4 < 4.8.1 only to require >= 4.8.0...

I suggest we can now change to requiring >= 4.8.1 (Ubuntu 20.0.4 LTS has 4.8.2). I've got a couple of other minor changes (and can add the CGI Python 3 one) - I'll propose a 10.0.1.

**Comment by anarcat** [comment]
thanks, i should probably just hardcode >= 4.8.1 in the package at least to make that clear, but i can also wait for 10.0.1
