### ISSUE TITLE
crashes with AttributeError: module 'bs4.builder'...

### ISSUE THREAD

**Issue by crysman** [linkchecker/linkchecker#699]
## Summary

crashes with `AttributeError: module 'bs4.builder' has no attribute 'XMLParsedAsHTMLWarning'`

## Steps to reproduce

 1. pip3 install linkchecker
 2. linkchecker https://simplecss.org/

## Actual result

```
% pip3 show linkchecker && pip3 check; linkchecker https://simplecss.org 
Name: LinkChecker
Version: 10.2.0
Summary: check links in web documents or full websites
Home-page: 
Author: LinkChecker Authors
Author-email: 
License: 
Location: /home/crysman/.local/lib/python3.10/site-packages
Requires: beautifulsoup4, dnspython, requests
Required-by: 
pynacl 1.5.0 requires cffi, which is not installed.
Traceback (most recent call last):
  File "/home/crysman/.local/bin/linkchecker", line 5, in <module>
    from linkcheck.command.linkchecker import linkchecker
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/command/linkchecker.py", line 28, in <module>
    from .arg_parser import ArgParser
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/command/arg_parser.py", line 22, in <module>
    from .. import checker, logconf, logger, COMMAND_NAME
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/checker/__init__.py", line 206, in <module>
    from . import (  # noqa: E402
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/checker/fileurl.py", line 26, in <module>
    from . import urlbase, get_index_html
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/checker/urlbase.py", line 38, in <module>
    from ..htmlutil import htmlsoup
  File "/home/crysman/.local/lib/python3.10/site-packages/linkcheck/htmlutil/htmlsoup.py", line 36, in <module>
    'ignore', bs4.builder.XMLParsedAsHTMLWarning
AttributeError: module 'bs4.builder' has no attribute 'XMLParsedAsHTMLWarning'
```

## Environment

 * Operating system: Pop!_OS 22.04 LTS
 * Linkchecker version: see above
 * Python version: 
 ```
% python --version
Python 3.10.6
```
 * Install method: pip3

## Configuration file

```
% cat ~/.config/linkchecker/linkcheckerrc
cat: /home/myuser/.config/linkchecker/linkcheckerrc: No such file or directory
```

:disappointed:

**Comment by crysman** [comment]
> To get it working: `pip3 install -U beautifulsoup4`

this workaround makes it roll! :heart:
