### ISSUE TITLE
Python 3.13: AttributeError: module 'importlib.resources' has no attribute 'path'

### ISSUE THREAD

**Issue by hroncok** [linkchecker/linkchecker#768]
## Summary

Hello. In Fedora we try to build our packages with early prerelease of Python 3.13 to discover problems early.

One of the packages is linkchecker, which fails (version 10.3.0, but the code is here on master as well) with:

```
=================================== FAILURES ===================================
_______________________ TestLinkchecker.test_linkchecker _______________________
[gw2] linux -- Python 3.13.0 /usr/bin/python3
tests/test_linkchecker.py:40: in test_linkchecker
    run_with_options([option])
tests/test_linkchecker.py:22: in run_with_options
    run_checked([sys.executable, "-m", "linkcheck"] + options)
tests/__init__.py:55: in run_checked
    raise OSError(msg)
E   OSError: Command `['/usr/bin/python3', '-m', 'linkcheck', '-V']' returned non-zero exit status 1
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/builddir/build/BUILD/LinkChecker-10.3.0/linkcheck/__main__.py", line 3, in <module>
    linkchecker()
  File "/builddir/build/BUILD/LinkChecker-10.3.0/linkcheck/command/linkchecker.py", line 143, in linkchecker
    config.read(files=files)
  File "/builddir/build/BUILD/LinkChecker-10.3.0/linkcheck/configuration/__init__.py", line 219, in read
    userconf = get_user_config()
               ^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/LinkChecker-10.3.0/linkcheck/configuration/__init__.py", line 388, in get_user_config
    with importlib.resources.path(
         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'importlib.resources' has no attribute 'path'
```

This comes from 
https://github.com/linkchecker/linkchecker/blob/8ae3783c3ffcb10ea1d72f9e8ee5deed674979db/linkcheck/configuration/__init__.py#L388

## Steps to reproduce

I've tried reproducing with `tox -e py313` but I am getting unrelated `ImportError: PyO3 modules may only be initialized once per interpreter process` errors from cryptography :(

## Environment

 * Operating system: Fedora Linux 39 
 * Linkchecker version: 10.3.0
 * Python version: 3.13.0a1
 * Install method: building the RPM package from sources, running pytest

## Configuration

N/A this is in the tests

## Logs

[build.log.txt](https://github.com/linkchecker/linkchecker/files/13222128/build.log.txt)

## Other notes

This was indeed removed from Python 3.13, the removal was recently documented in https://github.com/python/cpython/commit/3dbaed3caa00062087a848740b6e713ad55b0aed

I might be able to send a PR in upcoming weeks, but not currently.

**Comment by hroncok** [comment]
> Nor does the Python 3.12.0 documentation state that this is going to be removed in Python 3.13 (or 3.14).

I believe we try to get that better in https://github.com/python/cpython/issues/111301

**Comment by befeleme** [comment]
> > Nor does the Python 3.12.0 documentation state that this is going to be removed in Python 3.13 (or 3.14).
> 
> I believe we try to get that better in [python/cpython#111301](https://github.com/python/cpython/issues/111301)

That's indeed a good remark, I sent a PR to update 3.12 docs: https://github.com/python/cpython/pull/111630
