### ISSUE TITLE
cannot start linkchecker on global installation (pip)

### ISSUE THREAD

**Issue by durgaBahadur** [linkchecker/linkchecker#826]
## Summary

I cannot start `linkchecker`:

```
root@5e5e6208c180:/app/project# linkchecker
Traceback (most recent call last):
  File "/usr/local/bin/linkchecker", line 5, in <module>
    from linkcheck.command.linkchecker import linkchecker
  File "/usr/local/lib/python3.12/site-packages/linkcheck/command/linkchecker.py", line 28, in <module>
    from .arg_parser import ArgParser
  File "/usr/local/lib/python3.12/site-packages/linkcheck/command/arg_parser.py", line 22, in <module>
    from .. import checker, logconf, logger, COMMAND_NAME
  File "/usr/local/lib/python3.12/site-packages/linkcheck/checker/__init__.py", line 24, in <module>
    from .. import url as urlutil, log, LOG_CHECK
ImportError: cannot import name 'LOG_CHECK' from 'linkcheck' (/usr/local/lib/python3.12/site-packages/linkcheck/__init__.py)
```

## Steps to reproduce
```
 1. Install `linkchecker` globally with pip:
```
root@5e5e6208c180:/app/project# pip install linkchecker
```
 
2.   Run `linkchecker`
```
root@5e5e6208c180:/app/project# linkchecker
```

## Actual result

`linkchecker` produces the above error and exits.

## Expected result

`linkchecker` should run and check liniks.

## Environment

 * Operating system: 
 ```
root@5e5e6208c180:/app/project# uname -a
Linux 5e5e6208c180 6.6.35 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jun 21 12:38:50 UTC 2024 x86_64 GNU/Linux
```
 * Linkchecker version: 10.4.0
 * Python version: 3.12.4
 * Install method: PyPI

## Configuration

Just the default configuration after a fresh install through pip.

**Comment by gittieandpete** [comment]
Same with me on Ubuntu 22.04 Jammy, updated from 20.04
Traceback (most recent call last):
  File "/usr/local/bin/linkchecker", line 4, in <module>
    __import__('pkg_resources').run_script('LinkChecker==10.0.1', 'linkchecker')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/linkchecker' not found in metadata at '/usr/lib/python3/dist-packages/LinkChecker-10.0.1.egg-info'
